<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Estimate the ATE by TMLE | Inserm Workshop 282 - practical session</title>
  <meta name="description" content="Chapter 4 Estimate the ATE by TMLE | Inserm Workshop 282 - practical session" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Estimate the ATE by TMLE | Inserm Workshop 282 - practical session" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Chapter 4 Estimate the ATE by TMLE | Inserm Workshop 282 - practical session" />
  <meta name="github-repo" content="Inserm_workshop_282" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Estimate the ATE by TMLE | Inserm Workshop 282 - practical session" />
  
  <meta name="twitter:description" content="Chapter 4 Estimate the ATE by TMLE | Inserm Workshop 282 - practical session" />
  

<meta name="author" content="Benoît Lepage" />


<meta name="date" content="2025-10-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="applying-the-cmaverse.html"/>
<link rel="next" href="estimate-the-cde-using-the-ltmle-package.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Inserm_workshop_282</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data-generating-system"><i class="fa fa-check"></i><b>1.1</b> Data generating system</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reminders---estimate-the-ate.html"><a href="reminders---estimate-the-ate.html"><i class="fa fa-check"></i><b>2</b> Reminders - Estimate the ATE</a>
<ul>
<li class="chapter" data-level="2.1" data-path="reminders---estimate-the-ate.html"><a href="reminders---estimate-the-ate.html#estimation-of-the-average-total-effect-ate-by-g-computation"><i class="fa fa-check"></i><b>2.1</b> Estimation of the Average Total Effect (ATE) by g-computation</a></li>
<li class="chapter" data-level="2.2" data-path="reminders---estimate-the-ate.html"><a href="reminders---estimate-the-ate.html#estimation-of-the-ate-by-iptw"><i class="fa fa-check"></i><b>2.2</b> Estimation of the ATE by IPTW</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="reminders---estimate-the-ate.html"><a href="reminders---estimate-the-ate.html#classic-horvitz-thompson-estimator"><i class="fa fa-check"></i><b>2.2.1</b> “Classic” Horvitz Thompson estimator</a></li>
<li class="chapter" data-level="2.2.2" data-path="reminders---estimate-the-ate.html"><a href="reminders---estimate-the-ate.html#stabilized-iptw-for-the-ate"><i class="fa fa-check"></i><b>2.2.2</b> Stabilized IPTW for the ATE</a></li>
<li class="chapter" data-level="2.2.3" data-path="reminders---estimate-the-ate.html"><a href="reminders---estimate-the-ate.html#using-an-msm-estimated-by-iptw"><i class="fa fa-check"></i><b>2.2.3</b> Using an MSM estimated by IPTW</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="applying-the-cmaverse.html"><a href="applying-the-cmaverse.html"><i class="fa fa-check"></i><b>3</b> Applying the CMAverse</a>
<ul>
<li class="chapter" data-level="3.1" data-path="applying-the-cmaverse.html"><a href="applying-the-cmaverse.html#estimation-by-parametric-g-computation"><i class="fa fa-check"></i><b>3.1</b> Estimation by “parametric” g-computation</a></li>
<li class="chapter" data-level="3.2" data-path="applying-the-cmaverse.html"><a href="applying-the-cmaverse.html#estimation-by-msm-estimated-by-iptw"><i class="fa fa-check"></i><b>3.2</b> Estimation by MSM estimated by IPTW</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="estimate-the-ate-by-tmle.html"><a href="estimate-the-ate-by-tmle.html"><i class="fa fa-check"></i><b>4</b> Estimate the ATE by TMLE</a>
<ul>
<li class="chapter" data-level="4.1" data-path="estimate-the-ate-by-tmle.html"><a href="estimate-the-ate-by-tmle.html#tmle-for-the-ate"><i class="fa fa-check"></i><b>4.1</b> TMLE for the ATE</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html"><i class="fa fa-check"></i><b>5</b> Estimate the CDE using the <code>ltmle</code> package</a>
<ul>
<li class="chapter" data-level="5.1" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#ChapGcomp-CDE-ICE"><i class="fa fa-check"></i><b>5.1</b> G-computation by iterative conditional expectation</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#algorithm-and-manual-calculation"><i class="fa fa-check"></i><b>5.1.1</b> Algorithm and manual calculation</a></li>
<li class="chapter" data-level="5.1.2" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#g-computation-by-ice-using-the-ltmle-package"><i class="fa fa-check"></i><b>5.1.2</b> G-computation by ICE using the <code>ltmle</code> package</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#iptw-estimator-of-the-cde"><i class="fa fa-check"></i><b>5.2</b> IPTW estimator of the CDE</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#estimation-of-the-msm-coefficients-by-iptw"><i class="fa fa-check"></i><b>5.2.1</b> Estimation of the MSM coefficients by IPTW</a></li>
<li class="chapter" data-level="5.2.2" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#iptw-estmation-using-the-ltmle-package"><i class="fa fa-check"></i><b>5.2.2</b> IPTW estmation using the ltmle package</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#tmle-estimator-of-the-cde"><i class="fa fa-check"></i><b>5.3</b> TMLE estimator of the CDE</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#for-binary-outcomes"><i class="fa fa-check"></i><b>5.3.1</b> For binary outcomes</a></li>
<li class="chapter" data-level="5.3.2" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#for-continuous-outcomes"><i class="fa fa-check"></i><b>5.3.2</b> For continuous outcomes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="estimate-rnde-and-rnie-by-double-robust-estimators.html"><a href="estimate-rnde-and-rnie-by-double-robust-estimators.html"><i class="fa fa-check"></i><b>6</b> Estimate rNDE and rNIE by double robust estimators</a>
<ul>
<li class="chapter" data-level="6.1" data-path="estimate-rnde-and-rnie-by-double-robust-estimators.html"><a href="estimate-rnde-and-rnie-by-double-robust-estimators.html#g-computation-algorithm-to-compute-randomized-natural-direct-and-indirect-effects"><i class="fa fa-check"></i><b>6.1</b> G-computation algorithm to compute randomized Natural Direct and Indirect effects</a></li>
<li class="chapter" data-level="6.2" data-path="estimate-rnde-and-rnie-by-double-robust-estimators.html"><a href="estimate-rnde-and-rnie-by-double-robust-estimators.html#packages-to-get-double-robust-estimations"><i class="fa fa-check"></i><b>6.2</b> Packages to get double robust estimations</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ltmle-package-with-interval-censored-survival-data.html"><a href="ltmle-package-with-interval-censored-survival-data.html"><i class="fa fa-check"></i><b>7</b> <code>ltmle</code> package with interval censored survival data</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ltmle-package-with-interval-censored-survival-data.html"><a href="ltmle-package-with-interval-censored-survival-data.html#setting"><i class="fa fa-check"></i><b>7.1</b> Setting</a></li>
<li class="chapter" data-level="7.2" data-path="ltmle-package-with-interval-censored-survival-data.html"><a href="ltmle-package-with-interval-censored-survival-data.html#data-generating-function"><i class="fa fa-check"></i><b>7.2</b> Data generating function</a></li>
<li class="chapter" data-level="7.3" data-path="ltmle-package-with-interval-censored-survival-data.html"><a href="ltmle-package-with-interval-censored-survival-data.html#inspect-the-data-generated"><i class="fa fa-check"></i><b>7.3</b> Inspect the data generated</a></li>
<li class="chapter" data-level="7.4" data-path="ltmle-package-with-interval-censored-survival-data.html"><a href="ltmle-package-with-interval-censored-survival-data.html#estimate-the-controlled-direct-effect"><i class="fa fa-check"></i><b>7.4</b> Estimate the controlled direct effect</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Inserm Workshop 282 - practical session</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estimate-the-ate-by-tmle" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Estimate the ATE by TMLE<a href="estimate-the-ate-by-tmle.html#estimate-the-ate-by-tmle" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>When estimating a mean counterfactual outcome using g-computation methods, we have to estimate some <span class="math inline">\(\bar{Q}\)</span> functions (functions of the outcome conditional on the exposures and confounders, <span class="math inline">\(\bar{Q}=\mathbb{E}\left(Y\mid A,L(0)\right)\)</span>). For example, the Average Total Effect (ATE) is defined as a marginal effect, estimated using the empirical mean of such <span class="math inline">\(\bar{Q}\)</span> functions:
<span class="math display">\[\begin{equation*}
\hat{\Psi}^{\text{ATE}}_{\text{gcomp}} = \frac{1}{n} \sum_{i=1}^n \left[ \hat{\overline{Q}}(A=1)_i - \hat{\overline{Q}}(A=0)_i \right]
\end{equation*}\]</span></p>
<p>Unless the <span class="math inline">\(\bar{Q}\)</span> functions are not misspecified, its estimate is expected to be biased (and <span class="math inline">\(\bar{Q}\)</span> are expected to be misspecified, especially if the set of baseline confounders <span class="math inline">\(L(0)\)</span> is high dimensional, for example if it includes is a large number of variables or continuous variables). In order to improve the estimation of <span class="math inline">\(\bar{Q}(A,L)\)</span>, it is possible to use data-adaptive methods (machine learning algorithms) in order to optimize the bias-variance trade-off. However, this bias-variance trade-off would be optimized for the <span class="math inline">\(\bar{Q}\)</span> functions, not for the ATE estimate <span class="math inline">\(\hat{\Psi}^\text{ATE}_\text{gcomp}\)</span>. If the <span class="math inline">\(\bar{Q}\)</span> function is unknown and has to be estimated (preferably by data-adaptive methods), it can be shown that the g-computation estimate of <span class="math inline">\(\Psi^\text{ATE}\)</span> is asymptotically biased.</p>
<p>The Targeted Maximum Likelihood Estimation (TMLE) method has been developed as an asymptotically linear estimator, so that the estimation of any target parameter in any semiparametric statistical model is unbiased and efficient. In order to estimate a parameter <span class="math inline">\(\Psi(P_0)\)</span>, where <span class="math inline">\(P_0\)</span> is an unknown probability distribution among a set <span class="math inline">\(\mathcal{M}\)</span> of possible statistical models, the TMLE is described as a two-step procedure <span class="citation">(<a href="#ref-vanderlaan_book2011">Laan and Rose 2011</a>)</span>:</p>
<ul>
<li>The first step is to obtain an initial estimate of the relevant part (<span class="math inline">\(\bar{Q}_0\)</span> in our applications) of the probability distribution <span class="math inline">\(P_0\)</span>. Data adaptive methods (machine learning algorithms) can be used to optimize this first step.</li>
<li>The second step is to update the initial fit in order to “target toward making an optimal bias-variance tradeoff for the parameter of interest” <span class="math inline">\(\Psi(\bar{Q})\)</span>.</li>
</ul>
<p>Several R packages have been developed in order to carry out TMLE estimation of causal effects. We will begin using the <code>ltmle</code> package, as it can be used to estimate ATE or CDE. More generally, this package can be used to estimate the counterfactual effects of repeated exposure in time-to-event settings. In the setting of mediation analysis, a controlled direct effect (CDE) corresponds to a sequence of counterfactual interventions on 2 “exposure variables”: the initial exposure <span class="math inline">\(A\)</span> and the mediator of interest <span class="math inline">\(M\)</span>. The package can also be used in simpler settings with only one binary or continuous outcome, measure only once at the end a the study.</p>
<div id="tmle-for-the-ate" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> TMLE for the ATE<a href="estimate-the-ate-by-tmle.html#tmle-for-the-ate" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In order to illustrate the TMLE procedure, the estimation of a mean counterfactual outcome, denoted <span class="math inline">\(\Psi(A=1) = \mathbb{E} \left[\bar{Q}(A=1,L(0))\right]\)</span>, will be described in detail, following the algorithm implemented in the <code>ltmle</code> package.</p>
<p>The basic steps of the procedure are the following <span class="citation">(<a href="#ref-vanderlaan_book2011">Laan and Rose 2011</a>)</span>:</p>
<ol style="list-style-type: decimal">
<li><p>Estimate <span class="math inline">\(\bar{Q}_0\)</span>. Data-adaptive methods can be used here, the <code>ltmle</code> package relies on the <code>SuperLearner</code> package to fit and predict <span class="math inline">\(\hat{\bar{Q}}(A=1)\)</span>.</p></li>
<li><p>Estimate the treatment mechanism (propensity score) <span class="math inline">\(g(A=1 \mid L(0))\)</span>. Once again, data-adaptive methods can be used to improve the estimation.</p></li>
<li><p>The initial estimator of <span class="math inline">\(\bar{Q}_0(A=1)\)</span> will be slightly modified using a parametric fluctuation model, in order to reduce the bias when estimating the ATE. For example, the following parametric model of <span class="math inline">\(\bar{Q}_0(A=1)\)</span> and a “clever covariate” <span class="math inline">\(H = \frac{I(A=1)}{\hat{g}(A=1 \mid L(0))}\)</span> can be applied:
<span class="math display">\[\begin{equation*}
\text{logit} P(Y \mid \hat{\bar{Q}}, H) = \hat{\text{logit} \bar{Q}} + \varepsilon H
\end{equation*}\]</span>
This parametric fluctuation model is chosen so that the derivative of its log-likelihood loss function is equal to the appropriate component of the efficient influence curve of the target parameter <span class="math inline">\(\Psi(A=1)\)</span>.</p></li>
<li><p>Modify the initial estimator of <span class="math inline">\(\bar{Q}_0(A=1)\)</span> with the parametric fluctuation model (using the estimation <span class="math inline">\(\hat{\varepsilon}\)</span> from the previous step). We denote <span class="math inline">\(\hat{\bar{Q}}^*(A=1)\)</span> the updated value of <span class="math inline">\(\hat{\bar{Q}}(A=1)\)</span></p></li>
<li><p>Use the updated values <span class="math inline">\(\hat{\bar{Q}}^*(A=1)\)</span> in the substitution estimator to estimate the target parameter <span class="math inline">\(\Psi(A=1)\)</span> :
<span class="math display">\[\begin{equation*}
\hat{\Psi}(A=1)_\text{TMLE} = \frac{1}{n} \sum_{i=1}^n \hat{\bar{Q}}^* (A=1,L(0))
\end{equation*}\]</span></p></li>
<li><p>Estimate the efficient influence curve <span class="math inline">\(D^*(Q_0,g_0)\)</span> :
<span class="math display">\[\begin{equation*}
D^*(Q_0,g_0) = \frac{I(A=1)}{g_0(A=1 \mid L(0))}(Y - \bar{Q}_0(A,L(O))) + \bar{Q}_0(A=1,L(0))  - \Psi(A=1)
\end{equation*}\]</span></p></li>
</ol>
<p>The variance of the target parameter can then be calculated using the variance of the efficient influence curve:
<span class="math display">\[\begin{equation*}
\text{var} \hat{\Psi}(A=1)_\text{TMLE} = \frac{\text{var} \hat{D}^*}{n}
\end{equation*}\]</span></p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="estimate-the-ate-by-tmle.html#cb49-1" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb49-2"><a href="estimate-the-ate-by-tmle.html#cb49-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">&quot;data/df.csv&quot;</span>)</span>
<span id="cb49-3"><a href="estimate-the-ate-by-tmle.html#cb49-3" tabindex="-1"></a></span>
<span id="cb49-4"><a href="estimate-the-ate-by-tmle.html#cb49-4" tabindex="-1"></a><span class="do">## 1) Estimate Qbar and predict Qbar when the exposure (&quot;education&quot;) is set to 1</span></span>
<span id="cb49-5"><a href="estimate-the-ate-by-tmle.html#cb49-5" tabindex="-1"></a>Q_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(death <span class="sc">~</span> edu <span class="sc">+</span> sex <span class="sc">+</span> low_par_edu,</span>
<span id="cb49-6"><a href="estimate-the-ate-by-tmle.html#cb49-6" tabindex="-1"></a>             <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="at">data =</span> df)</span>
<span id="cb49-7"><a href="estimate-the-ate-by-tmle.html#cb49-7" tabindex="-1"></a>data_A1 <span class="ot">&lt;-</span> df</span>
<span id="cb49-8"><a href="estimate-the-ate-by-tmle.html#cb49-8" tabindex="-1"></a>data_A1<span class="sc">$</span>edu <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb49-9"><a href="estimate-the-ate-by-tmle.html#cb49-9" tabindex="-1"></a></span>
<span id="cb49-10"><a href="estimate-the-ate-by-tmle.html#cb49-10" tabindex="-1"></a><span class="co"># predict the Qvar function when setting the exposure to A=1, on the logit scale</span></span>
<span id="cb49-11"><a href="estimate-the-ate-by-tmle.html#cb49-11" tabindex="-1"></a>logitQ <span class="ot">&lt;-</span> <span class="fu">predict</span>(Q_fit, <span class="at">newdata =</span> data_A1, <span class="at">type =</span> <span class="st">&quot;link&quot;</span>)</span>
<span id="cb49-12"><a href="estimate-the-ate-by-tmle.html#cb49-12" tabindex="-1"></a></span>
<span id="cb49-13"><a href="estimate-the-ate-by-tmle.html#cb49-13" tabindex="-1"></a><span class="do">## 2) Estimate the treatment mechanism</span></span>
<span id="cb49-14"><a href="estimate-the-ate-by-tmle.html#cb49-14" tabindex="-1"></a>g_L <span class="ot">&lt;-</span> <span class="fu">glm</span>(edu <span class="sc">~</span> sex <span class="sc">+</span> low_par_edu,</span>
<span id="cb49-15"><a href="estimate-the-ate-by-tmle.html#cb49-15" tabindex="-1"></a>           <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="at">data =</span> df)</span>
<span id="cb49-16"><a href="estimate-the-ate-by-tmle.html#cb49-16" tabindex="-1"></a><span class="co"># predict the probabilities g(A=1 | L(0)) = P(A0_PM2.5=1|L(0))</span></span>
<span id="cb49-17"><a href="estimate-the-ate-by-tmle.html#cb49-17" tabindex="-1"></a>g1_L <span class="ot">&lt;-</span> <span class="fu">predict</span>(g_L, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb49-18"><a href="estimate-the-ate-by-tmle.html#cb49-18" tabindex="-1"></a></span>
<span id="cb49-19"><a href="estimate-the-ate-by-tmle.html#cb49-19" tabindex="-1"></a><span class="fu">head</span>(g1_L)</span></code></pre></div>
<pre><code>##         1         2         3         4         5         6 
## 0.6608369 0.6071248 0.6071248 0.4495011 0.6071248 0.6071248</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="estimate-the-ate-by-tmle.html#cb51-1" tabindex="-1"></a><span class="co"># It is useful to check the distribution of gA_L, as values close to 0 or 1 are </span></span>
<span id="cb51-2"><a href="estimate-the-ate-by-tmle.html#cb51-2" tabindex="-1"></a><span class="co"># indicators of near positivity violation and can result in large variance for the </span></span>
<span id="cb51-3"><a href="estimate-the-ate-by-tmle.html#cb51-3" tabindex="-1"></a><span class="co"># estimation. </span></span>
<span id="cb51-4"><a href="estimate-the-ate-by-tmle.html#cb51-4" tabindex="-1"></a><span class="co"># In case of near positivity violation, gA_L values can be truncated to decrease</span></span>
<span id="cb51-5"><a href="estimate-the-ate-by-tmle.html#cb51-5" tabindex="-1"></a><span class="co"># the variance (at the cost a increased bias).</span></span>
<span id="cb51-6"><a href="estimate-the-ate-by-tmle.html#cb51-6" tabindex="-1"></a><span class="fu">summary</span>(g1_L)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.4495  0.5073  0.6071  0.5953  0.6608  0.6608</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="estimate-the-ate-by-tmle.html#cb53-1" tabindex="-1"></a><span class="co"># there is no positivity issues in this example.</span></span>
<span id="cb53-2"><a href="estimate-the-ate-by-tmle.html#cb53-2" tabindex="-1"></a></span>
<span id="cb53-3"><a href="estimate-the-ate-by-tmle.html#cb53-3" tabindex="-1"></a><span class="do">## 3) Determine a parametric family of fluctuations of Qbar. </span></span>
<span id="cb53-4"><a href="estimate-the-ate-by-tmle.html#cb53-4" tabindex="-1"></a><span class="co"># The fluctuation model is a model of logitQbar and g(A=1|L(0)) </span></span>
<span id="cb53-5"><a href="estimate-the-ate-by-tmle.html#cb53-5" tabindex="-1"></a></span>
<span id="cb53-6"><a href="estimate-the-ate-by-tmle.html#cb53-6" tabindex="-1"></a><span class="co"># The clever covariate H(A,L(0)) depends on g(A=1|L(0)):</span></span>
<span id="cb53-7"><a href="estimate-the-ate-by-tmle.html#cb53-7" tabindex="-1"></a>H <span class="ot">&lt;-</span> (df<span class="sc">$</span>edu <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">/</span> g1_L</span>
<span id="cb53-8"><a href="estimate-the-ate-by-tmle.html#cb53-8" tabindex="-1"></a></span>
<span id="cb53-9"><a href="estimate-the-ate-by-tmle.html#cb53-9" tabindex="-1"></a><span class="co"># Update the initial fit Qbar from step 1.</span></span>
<span id="cb53-10"><a href="estimate-the-ate-by-tmle.html#cb53-10" tabindex="-1"></a><span class="co"># This is achieved by holding Qbar fixed (as intercept) while estimating the</span></span>
<span id="cb53-11"><a href="estimate-the-ate-by-tmle.html#cb53-11" tabindex="-1"></a><span class="co"># coefficient epsilon for H</span></span>
<span id="cb53-12"><a href="estimate-the-ate-by-tmle.html#cb53-12" tabindex="-1"></a></span>
<span id="cb53-13"><a href="estimate-the-ate-by-tmle.html#cb53-13" tabindex="-1"></a><span class="co"># for example we could use the following fluctuation model (from the &quot;Targeted </span></span>
<span id="cb53-14"><a href="estimate-the-ate-by-tmle.html#cb53-14" tabindex="-1"></a><span class="co"># Learning&quot; book)</span></span>
<span id="cb53-15"><a href="estimate-the-ate-by-tmle.html#cb53-15" tabindex="-1"></a>update_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(df<span class="sc">$</span>death <span class="sc">~</span> <span class="sc">-</span><span class="dv">1</span> <span class="sc">+</span> <span class="fu">offset</span>(logitQ) <span class="sc">+</span> H,</span>
<span id="cb53-16"><a href="estimate-the-ate-by-tmle.html#cb53-16" tabindex="-1"></a>                  <span class="at">family =</span> <span class="st">&quot;quasibinomial&quot;</span>)</span>
<span id="cb53-17"><a href="estimate-the-ate-by-tmle.html#cb53-17" tabindex="-1"></a><span class="fu">coef</span>(update_fit)</span></code></pre></div>
<pre><code>##             H 
## -1.658129e-05</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="estimate-the-ate-by-tmle.html#cb55-1" tabindex="-1"></a>Qstar <span class="ot">&lt;-</span> <span class="fu">predict</span>(update_fit, <span class="at">data =</span> <span class="fu">data.frame</span>(logitQ, H), <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb55-2"><a href="estimate-the-ate-by-tmle.html#cb55-2" tabindex="-1"></a></span>
<span id="cb55-3"><a href="estimate-the-ate-by-tmle.html#cb55-3" tabindex="-1"></a><span class="co"># In the ltmle package, the fluctuation parametric model is slightly different</span></span>
<span id="cb55-4"><a href="estimate-the-ate-by-tmle.html#cb55-4" tabindex="-1"></a><span class="co"># (but with the same purpose). The &quot;clever covariate&quot; H is scaled and used as a </span></span>
<span id="cb55-5"><a href="estimate-the-ate-by-tmle.html#cb55-5" tabindex="-1"></a><span class="co"># weight in the parametric quasi-logistic regression</span></span>
<span id="cb55-6"><a href="estimate-the-ate-by-tmle.html#cb55-6" tabindex="-1"></a>S1 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(df))</span>
<span id="cb55-7"><a href="estimate-the-ate-by-tmle.html#cb55-7" tabindex="-1"></a>update_fit_ltmle <span class="ot">&lt;-</span> <span class="fu">glm</span>(df<span class="sc">$</span>death <span class="sc">~</span> <span class="sc">-</span><span class="dv">1</span> <span class="sc">+</span> S1 <span class="sc">+</span> <span class="fu">offset</span>(logitQ),</span>
<span id="cb55-8"><a href="estimate-the-ate-by-tmle.html#cb55-8" tabindex="-1"></a>                        <span class="at">family =</span> <span class="st">&quot;quasibinomial&quot;</span>,</span>
<span id="cb55-9"><a href="estimate-the-ate-by-tmle.html#cb55-9" tabindex="-1"></a>                        <span class="at">weights =</span> <span class="fu">scale</span>(H, <span class="at">center =</span> <span class="cn">FALSE</span>))</span>
<span id="cb55-10"><a href="estimate-the-ate-by-tmle.html#cb55-10" tabindex="-1"></a><span class="fu">coef</span>(update_fit_ltmle)</span></code></pre></div>
<pre><code>##           S1 
## -2.80861e-05</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="estimate-the-ate-by-tmle.html#cb57-1" tabindex="-1"></a><span class="do">## 4) Update the initial estimate of Qbar using the fluctuation parametric model</span></span>
<span id="cb57-2"><a href="estimate-the-ate-by-tmle.html#cb57-2" tabindex="-1"></a>Qstar_ltmle <span class="ot">&lt;-</span> <span class="fu">predict</span>(update_fit_ltmle, </span>
<span id="cb57-3"><a href="estimate-the-ate-by-tmle.html#cb57-3" tabindex="-1"></a>                       <span class="at">data =</span> <span class="fu">data.frame</span>(logitQ, H), </span>
<span id="cb57-4"><a href="estimate-the-ate-by-tmle.html#cb57-4" tabindex="-1"></a>                       <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb57-5"><a href="estimate-the-ate-by-tmle.html#cb57-5" tabindex="-1"></a><span class="fu">head</span>(Qstar_ltmle)</span></code></pre></div>
<pre><code>##         1         2         3         4         5         6 
## 0.3073922 0.4243074 0.4243074 0.3015693 0.4243074 0.4243074</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="estimate-the-ate-by-tmle.html#cb59-1" tabindex="-1"></a><span class="co">#         1         2         3         4         5         6 </span></span>
<span id="cb59-2"><a href="estimate-the-ate-by-tmle.html#cb59-2" tabindex="-1"></a><span class="co"># 0.2872412 0.3441344 0.3441344 0.2591356 0.3441344 0.3441344</span></span>
<span id="cb59-3"><a href="estimate-the-ate-by-tmle.html#cb59-3" tabindex="-1"></a></span>
<span id="cb59-4"><a href="estimate-the-ate-by-tmle.html#cb59-4" tabindex="-1"></a><span class="do">## 5) Obtain the substition estimator of Psi_Ais1</span></span>
<span id="cb59-5"><a href="estimate-the-ate-by-tmle.html#cb59-5" tabindex="-1"></a>Psi_Ais1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(Qstar_ltmle)</span>
<span id="cb59-6"><a href="estimate-the-ate-by-tmle.html#cb59-6" tabindex="-1"></a>Psi_Ais1</span></code></pre></div>
<pre><code>## [1] 0.3306626</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="estimate-the-ate-by-tmle.html#cb61-1" tabindex="-1"></a><span class="do">## 5) Calculate standard errors based on the influence curve of the TMLE</span></span>
<span id="cb61-2"><a href="estimate-the-ate-by-tmle.html#cb61-2" tabindex="-1"></a>IC <span class="ot">&lt;-</span> H <span class="sc">*</span> (df<span class="sc">$</span>death <span class="sc">-</span> Qstar_ltmle) <span class="sc">+</span> Qstar_ltmle <span class="sc">-</span> Psi_Ais1</span>
<span id="cb61-3"><a href="estimate-the-ate-by-tmle.html#cb61-3" tabindex="-1"></a><span class="fu">head</span>(IC)</span></code></pre></div>
<pre><code>##           1           2           3           4           5           6 
## -0.48842639  0.09364473  0.09364473  1.52469745  0.09364473  1.04187255</code></pre>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="estimate-the-ate-by-tmle.html#cb63-1" tabindex="-1"></a><span class="co"># the influence curve has a mean of 0</span></span>
<span id="cb63-2"><a href="estimate-the-ate-by-tmle.html#cb63-2" tabindex="-1"></a><span class="fu">summary</span>(IC)</span></code></pre></div>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## -0.69999 -0.48843 -0.02909  0.00000  0.09364  1.52470</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="estimate-the-ate-by-tmle.html#cb65-1" tabindex="-1"></a><span class="co"># The standard error of the target parameter Psi(A=1) can be estimated by :</span></span>
<span id="cb65-2"><a href="estimate-the-ate-by-tmle.html#cb65-2" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">var</span>(IC)<span class="sc">/</span><span class="fu">nrow</span>(df))</span></code></pre></div>
<pre><code>## [1] 0.006090826</code></pre>
<p>We can see that we can get the same output using the <code>ltmle</code> package (cf. <code>?ltmle</code> to see how the function works):</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="estimate-the-ate-by-tmle.html#cb67-1" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb67-2"><a href="estimate-the-ate-by-tmle.html#cb67-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">&quot;data/df.csv&quot;</span>)</span>
<span id="cb67-3"><a href="estimate-the-ate-by-tmle.html#cb67-3" tabindex="-1"></a></span>
<span id="cb67-4"><a href="estimate-the-ate-by-tmle.html#cb67-4" tabindex="-1"></a><span class="fu">library</span>(ltmle)</span>
<span id="cb67-5"><a href="estimate-the-ate-by-tmle.html#cb67-5" tabindex="-1"></a></span>
<span id="cb67-6"><a href="estimate-the-ate-by-tmle.html#cb67-6" tabindex="-1"></a><span class="co"># The Qform and gform arguments are defined from the DAG</span></span>
<span id="cb67-7"><a href="estimate-the-ate-by-tmle.html#cb67-7" tabindex="-1"></a>Qform <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">death=</span><span class="st">&quot;Q.kplus1 ~ sex + low_par_edu + edu&quot;</span>)</span>
<span id="cb67-8"><a href="estimate-the-ate-by-tmle.html#cb67-8" tabindex="-1"></a>gform <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;edu ~ sex + low_par_edu&quot;</span>)</span>
<span id="cb67-9"><a href="estimate-the-ate-by-tmle.html#cb67-9" tabindex="-1"></a></span>
<span id="cb67-10"><a href="estimate-the-ate-by-tmle.html#cb67-10" tabindex="-1"></a><span class="co"># in the ltmle package, the data set should be formated so that the order of the </span></span>
<span id="cb67-11"><a href="estimate-the-ate-by-tmle.html#cb67-11" tabindex="-1"></a><span class="co"># columns corresponds to the time-ordering of the model</span></span>
<span id="cb67-12"><a href="estimate-the-ate-by-tmle.html#cb67-12" tabindex="-1"></a>data_ltmle <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, </span>
<span id="cb67-13"><a href="estimate-the-ate-by-tmle.html#cb67-13" tabindex="-1"></a>                     <span class="at">select =</span> <span class="fu">c</span>(sex, low_par_edu, edu, death))</span>
<span id="cb67-14"><a href="estimate-the-ate-by-tmle.html#cb67-14" tabindex="-1"></a></span>
<span id="cb67-15"><a href="estimate-the-ate-by-tmle.html#cb67-15" tabindex="-1"></a><span class="co"># the counterfactual intervention is defined in the abar argument</span></span>
<span id="cb67-16"><a href="estimate-the-ate-by-tmle.html#cb67-16" tabindex="-1"></a>abar <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb67-17"><a href="estimate-the-ate-by-tmle.html#cb67-17" tabindex="-1"></a></span>
<span id="cb67-18"><a href="estimate-the-ate-by-tmle.html#cb67-18" tabindex="-1"></a>Psi_Ais1 <span class="ot">&lt;-</span> <span class="fu">ltmle</span>(data_ltmle,</span>
<span id="cb67-19"><a href="estimate-the-ate-by-tmle.html#cb67-19" tabindex="-1"></a>                  <span class="at">Anodes =</span> <span class="st">&quot;edu&quot;</span>,</span>
<span id="cb67-20"><a href="estimate-the-ate-by-tmle.html#cb67-20" tabindex="-1"></a>                  <span class="at">Ynodes =</span> <span class="st">&quot;death&quot;</span>,</span>
<span id="cb67-21"><a href="estimate-the-ate-by-tmle.html#cb67-21" tabindex="-1"></a>                  <span class="at">Qform =</span> Qform,</span>
<span id="cb67-22"><a href="estimate-the-ate-by-tmle.html#cb67-22" tabindex="-1"></a>                  <span class="at">gform =</span> gform,</span>
<span id="cb67-23"><a href="estimate-the-ate-by-tmle.html#cb67-23" tabindex="-1"></a>                  <span class="at">gbounds =</span> <span class="fu">c</span>(<span class="fl">0.01</span>, <span class="dv">1</span>), <span class="co"># by default, g function truncated at 0.01</span></span>
<span id="cb67-24"><a href="estimate-the-ate-by-tmle.html#cb67-24" tabindex="-1"></a>                  <span class="at">abar =</span> abar,</span>
<span id="cb67-25"><a href="estimate-the-ate-by-tmle.html#cb67-25" tabindex="-1"></a>                  <span class="at">SL.library =</span> <span class="st">&quot;glm&quot;</span>,</span>
<span id="cb67-26"><a href="estimate-the-ate-by-tmle.html#cb67-26" tabindex="-1"></a>                  <span class="at">variance.method =</span> <span class="st">&quot;ic&quot;</span>)</span>
<span id="cb67-27"><a href="estimate-the-ate-by-tmle.html#cb67-27" tabindex="-1"></a></span>
<span id="cb67-28"><a href="estimate-the-ate-by-tmle.html#cb67-28" tabindex="-1"></a><span class="co"># from the ltmle() function, we can get the point estimate, its standard error, </span></span>
<span id="cb67-29"><a href="estimate-the-ate-by-tmle.html#cb67-29" tabindex="-1"></a><span class="co"># 95% confidence interval and the p-value for the null hypothesis.</span></span>
<span id="cb67-30"><a href="estimate-the-ate-by-tmle.html#cb67-30" tabindex="-1"></a><span class="fu">summary</span>(Psi_Ais1, <span class="st">&quot;tmle&quot;</span>)</span></code></pre></div>
<pre><code>## Estimator:  tmle 
## Call:
## ltmle(data = data_ltmle, Anodes = &quot;edu&quot;, Ynodes = &quot;death&quot;, Qform = Qform, 
##     gform = gform, abar = abar, gbounds = c(0.01, 1), SL.library = &quot;glm&quot;, 
##     variance.method = &quot;ic&quot;)
## 
##    Parameter Estimate:  0.33066 
##     Estimated Std Err:  0.0060908 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (0.31872, 0.3426)</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="estimate-the-ate-by-tmle.html#cb69-1" tabindex="-1"></a><span class="co"># The ltmle() function returns an object with several outputs.</span></span>
<span id="cb69-2"><a href="estimate-the-ate-by-tmle.html#cb69-2" tabindex="-1"></a><span class="co"># We can see that g functions are the same as in the previous manual calculation</span></span>
<span id="cb69-3"><a href="estimate-the-ate-by-tmle.html#cb69-3" tabindex="-1"></a><span class="fu">head</span>(Psi_Ais1<span class="sc">$</span>cum.g)</span></code></pre></div>
<pre><code>##           [,1]
## [1,] 0.6608369
## [2,] 0.6071248
## [3,] 0.6071248
## [4,] 0.4495011
## [5,] 0.6071248
## [6,] 0.6071248</code></pre>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="estimate-the-ate-by-tmle.html#cb71-1" tabindex="-1"></a><span class="co"># we can get the estimation of the epsilon parameter from the fluctuation model</span></span>
<span id="cb71-2"><a href="estimate-the-ate-by-tmle.html#cb71-2" tabindex="-1"></a>Psi_Ais1<span class="sc">$</span>fit<span class="sc">$</span>Qstar</span></code></pre></div>
<pre><code>## $death
## 
## Call:  glm(formula = formula, family = family, data = data.frame(data, 
##     weights), weights = weights, control = glm.control(maxit = 100))
## 
## Coefficients:
##         S1  
## -2.809e-05  
## 
## Degrees of Freedom: 5953 Total (i.e. Null);  5952 Residual
## Null Deviance:       7342 
## Residual Deviance: 7342  AIC: NA</code></pre>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="estimate-the-ate-by-tmle.html#cb73-1" tabindex="-1"></a><span class="co"># we can get the updated Qbar functions:</span></span>
<span id="cb73-2"><a href="estimate-the-ate-by-tmle.html#cb73-2" tabindex="-1"></a><span class="fu">head</span>(Psi_Ais1<span class="sc">$</span>Qstar)</span></code></pre></div>
<pre><code>## [1] 0.3073922 0.4243074 0.4243074 0.3015693 0.4243074 0.4243074</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="estimate-the-ate-by-tmle.html#cb75-1" tabindex="-1"></a><span class="co"># we can get the influence curve </span></span>
<span id="cb75-2"><a href="estimate-the-ate-by-tmle.html#cb75-2" tabindex="-1"></a><span class="fu">head</span>(Psi_Ais1<span class="sc">$</span>IC<span class="sc">$</span>tmle)</span></code></pre></div>
<pre><code>## [1] -0.48842639  0.09364473  0.09364473  1.52469745  0.09364473  1.04187255</code></pre>
<p>In practice, it is recommended to apply data-adaptive algorithms to estimate <span class="math inline">\(\bar{Q}\)</span> and <span class="math inline">\(g\)</span> functions: the <code>ltmle</code> package relies on the <code>SuperLearner</code> package. As indicated in the <a href="https://cran.r-project.org/web/packages/SuperLearner/vignettes/Guide-to-SuperLearner.html">Guide to SuperLearner</a>,
The <code>SuperLearner</code> is “an algorithm that uses cross-validation to estimate the performance of multiple machine learning models, or the same model with different settings. It then creates an optimal weighted average of those models (ensemble learning) using the test data performance.”</p>
<p>Here is an example for our estimation of the Average Total Effect (ATE).</p>
<p>The <code>SuperLearner</code> package includes a set of algorithms with default parameters (showed by <code>listWrappers()</code>). Because the simulated data set only have 2 binary baseline variables, the set <span class="math inline">\(\mathcal{M}\)</span> of possible statistical models is limited. In order to estimate the ATE, we will include a library with:</p>
<ul>
<li><code>SL.mean</code>, the null-model which only predict the marginal mean (it can be used as a reference for a bad model);</li>
<li><code>SL.glm</code>, a glm using the main terms from the <code>Qform</code> and <code>gform</code> argument; We will also add a <code>screen</code> algorithm which first applies a selection prodedure on the predictors of the learner.</li>
<li><code>SL.interaction.back</code>, a step-by-step backward GLM prodecure (based on the AIC), starting with all <span class="math inline">\(2 \times 2\)</span> interactions between main terms. This function is customized from the <code>SL.step.interaction</code> available with the <code>ltmle</code> and <code>SuperLearner</code> packages, where the <code>direction</code> argument is set to <code>both</code> by default.</li>
<li><code>SL.hal9001</code> fit the “Highly Adaptive Lasso (HAL) algorithm. See the <a href="https://cran.r-project.org/web//packages/hal9001/vignettes/intro_hal9001.html">vignette</a> for more information on the HAL algorithm. One of its advantage is a very fast rate of convergence.</li>
</ul>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="estimate-the-ate-by-tmle.html#cb77-1" tabindex="-1"></a><span class="fu">library</span>(SuperLearner)</span>
<span id="cb77-2"><a href="estimate-the-ate-by-tmle.html#cb77-2" tabindex="-1"></a><span class="fu">library</span>(hal9001)</span>
<span id="cb77-3"><a href="estimate-the-ate-by-tmle.html#cb77-3" tabindex="-1"></a><span class="co"># Below, we use the same ltmle() function than previously, </span></span>
<span id="cb77-4"><a href="estimate-the-ate-by-tmle.html#cb77-4" tabindex="-1"></a><span class="co"># and specify a family of algorithms to be used with the SuperLearner</span></span>
<span id="cb77-5"><a href="estimate-the-ate-by-tmle.html#cb77-5" tabindex="-1"></a></span>
<span id="cb77-6"><a href="estimate-the-ate-by-tmle.html#cb77-6" tabindex="-1"></a><span class="do">## we can change the default argument of the SL.xgboost algorithm and the </span></span>
<span id="cb77-7"><a href="estimate-the-ate-by-tmle.html#cb77-7" tabindex="-1"></a><span class="do">## SL.step.interaction algorithm</span></span>
<span id="cb77-8"><a href="estimate-the-ate-by-tmle.html#cb77-8" tabindex="-1"></a></span>
<span id="cb77-9"><a href="estimate-the-ate-by-tmle.html#cb77-9" tabindex="-1"></a><span class="co"># We can check how arguments are used in the pre-specified algorithms</span></span>
<span id="cb77-10"><a href="estimate-the-ate-by-tmle.html#cb77-10" tabindex="-1"></a>SL.step.interaction</span></code></pre></div>
<pre><code>## function (Y, X, newX, family, direction = &quot;both&quot;, trace = 0, 
##     k = 2, ...) 
## {
##     fit.glm &lt;- glm(Y ~ ., data = X, family = family)
##     fit.step &lt;- step(fit.glm, scope = Y ~ .^2, direction = direction, 
##         trace = trace, k = k)
##     pred &lt;- predict(fit.step, newdata = newX, type = &quot;response&quot;)
##     fit &lt;- list(object = fit.step)
##     out &lt;- list(pred = pred, fit = fit)
##     class(out$fit) &lt;- c(&quot;SL.step&quot;)
##     return(out)
## }
## &lt;bytecode: 0x000002d74d308d60&gt;
## &lt;environment: namespace:SuperLearner&gt;</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="estimate-the-ate-by-tmle.html#cb79-1" tabindex="-1"></a><span class="co"># function (Y, X, newX, family, direction = &quot;both&quot;, trace = 0, </span></span>
<span id="cb79-2"><a href="estimate-the-ate-by-tmle.html#cb79-2" tabindex="-1"></a><span class="co">#     k = 2, ...) </span></span>
<span id="cb79-3"><a href="estimate-the-ate-by-tmle.html#cb79-3" tabindex="-1"></a><span class="co"># {</span></span>
<span id="cb79-4"><a href="estimate-the-ate-by-tmle.html#cb79-4" tabindex="-1"></a><span class="co">#     fit.glm &lt;- glm(Y ~ ., data = X, family = family)</span></span>
<span id="cb79-5"><a href="estimate-the-ate-by-tmle.html#cb79-5" tabindex="-1"></a><span class="co">#     fit.step &lt;- step(fit.glm, scope = Y ~ .^2, direction = direction, </span></span>
<span id="cb79-6"><a href="estimate-the-ate-by-tmle.html#cb79-6" tabindex="-1"></a><span class="co">#         trace = trace, k = k)</span></span>
<span id="cb79-7"><a href="estimate-the-ate-by-tmle.html#cb79-7" tabindex="-1"></a><span class="co">#     pred &lt;- predict(fit.step, newdata = newX, type = &quot;response&quot;)</span></span>
<span id="cb79-8"><a href="estimate-the-ate-by-tmle.html#cb79-8" tabindex="-1"></a><span class="co">#     fit &lt;- list(object = fit.step)</span></span>
<span id="cb79-9"><a href="estimate-the-ate-by-tmle.html#cb79-9" tabindex="-1"></a><span class="co">#     out &lt;- list(pred = pred, fit = fit)</span></span>
<span id="cb79-10"><a href="estimate-the-ate-by-tmle.html#cb79-10" tabindex="-1"></a><span class="co">#     class(out$fit) &lt;- c(&quot;SL.step&quot;)</span></span>
<span id="cb79-11"><a href="estimate-the-ate-by-tmle.html#cb79-11" tabindex="-1"></a><span class="co">#     return(out)</span></span>
<span id="cb79-12"><a href="estimate-the-ate-by-tmle.html#cb79-12" tabindex="-1"></a><span class="co"># }</span></span>
<span id="cb79-13"><a href="estimate-the-ate-by-tmle.html#cb79-13" tabindex="-1"></a><span class="co"># &lt;bytecode: 0x000001b965ed0dc0&gt;</span></span>
<span id="cb79-14"><a href="estimate-the-ate-by-tmle.html#cb79-14" tabindex="-1"></a><span class="co"># &lt;environment: namespace:SuperLearner&gt;</span></span>
<span id="cb79-15"><a href="estimate-the-ate-by-tmle.html#cb79-15" tabindex="-1"></a></span>
<span id="cb79-16"><a href="estimate-the-ate-by-tmle.html#cb79-16" tabindex="-1"></a><span class="co"># the SL.step.interaction can be adapted, changing some arguments:</span></span>
<span id="cb79-17"><a href="estimate-the-ate-by-tmle.html#cb79-17" tabindex="-1"></a>SL.interaction.back <span class="ot">=</span> <span class="cf">function</span>(...) {</span>
<span id="cb79-18"><a href="estimate-the-ate-by-tmle.html#cb79-18" tabindex="-1"></a>  <span class="fu">SL.step.interaction</span>(..., <span class="at">direction =</span> <span class="st">&quot;backward&quot;</span>)</span>
<span id="cb79-19"><a href="estimate-the-ate-by-tmle.html#cb79-19" tabindex="-1"></a>}</span>
<span id="cb79-20"><a href="estimate-the-ate-by-tmle.html#cb79-20" tabindex="-1"></a></span>
<span id="cb79-21"><a href="estimate-the-ate-by-tmle.html#cb79-21" tabindex="-1"></a><span class="do">## The HAL algorithm implemented by default does not deal correctly with </span></span>
<span id="cb79-22"><a href="estimate-the-ate-by-tmle.html#cb79-22" tabindex="-1"></a><span class="do">## continuous outcome, </span></span>
<span id="cb79-23"><a href="estimate-the-ate-by-tmle.html#cb79-23" tabindex="-1"></a><span class="do">## However, we can define your own learner algorithm, following the template:</span></span>
<span id="cb79-24"><a href="estimate-the-ate-by-tmle.html#cb79-24" tabindex="-1"></a>SL.template</span></code></pre></div>
<pre><code>## function (Y, X, newX, family, obsWeights, id, ...) 
## {
##     if (family$family == &quot;gaussian&quot;) {
##     }
##     if (family$family == &quot;binomial&quot;) {
##     }
##     pred &lt;- numeric()
##     fit &lt;- vector(&quot;list&quot;, length = 0)
##     class(fit) &lt;- c(&quot;SL.template&quot;)
##     out &lt;- list(pred = pred, fit = fit)
##     return(out)
## }
## &lt;bytecode: 0x000002d74d09d150&gt;
## &lt;environment: namespace:SuperLearner&gt;</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="estimate-the-ate-by-tmle.html#cb81-1" tabindex="-1"></a><span class="co"># function (Y, X, newX, family, obsWeights, id, ...) </span></span>
<span id="cb81-2"><a href="estimate-the-ate-by-tmle.html#cb81-2" tabindex="-1"></a><span class="co"># {</span></span>
<span id="cb81-3"><a href="estimate-the-ate-by-tmle.html#cb81-3" tabindex="-1"></a><span class="co">#     if (family$family == &quot;gaussian&quot;) {</span></span>
<span id="cb81-4"><a href="estimate-the-ate-by-tmle.html#cb81-4" tabindex="-1"></a><span class="co">#     }</span></span>
<span id="cb81-5"><a href="estimate-the-ate-by-tmle.html#cb81-5" tabindex="-1"></a><span class="co">#     if (family$family == &quot;binomial&quot;) {</span></span>
<span id="cb81-6"><a href="estimate-the-ate-by-tmle.html#cb81-6" tabindex="-1"></a><span class="co">#     }</span></span>
<span id="cb81-7"><a href="estimate-the-ate-by-tmle.html#cb81-7" tabindex="-1"></a><span class="co">#     pred &lt;- numeric()</span></span>
<span id="cb81-8"><a href="estimate-the-ate-by-tmle.html#cb81-8" tabindex="-1"></a><span class="co">#     fit &lt;- vector(&quot;list&quot;, length = 0)</span></span>
<span id="cb81-9"><a href="estimate-the-ate-by-tmle.html#cb81-9" tabindex="-1"></a><span class="co">#     class(fit) &lt;- c(&quot;SL.template&quot;)</span></span>
<span id="cb81-10"><a href="estimate-the-ate-by-tmle.html#cb81-10" tabindex="-1"></a><span class="co">#     out &lt;- list(pred = pred, fit = fit)</span></span>
<span id="cb81-11"><a href="estimate-the-ate-by-tmle.html#cb81-11" tabindex="-1"></a><span class="co">#     return(out)</span></span>
<span id="cb81-12"><a href="estimate-the-ate-by-tmle.html#cb81-12" tabindex="-1"></a><span class="co"># }</span></span>
<span id="cb81-13"><a href="estimate-the-ate-by-tmle.html#cb81-13" tabindex="-1"></a><span class="co"># &lt;bytecode: 0x00000291b737f2e0&gt;</span></span>
<span id="cb81-14"><a href="estimate-the-ate-by-tmle.html#cb81-14" tabindex="-1"></a><span class="co"># &lt;environment: namespace:SuperLearner&gt;</span></span>
<span id="cb81-15"><a href="estimate-the-ate-by-tmle.html#cb81-15" tabindex="-1"></a></span>
<span id="cb81-16"><a href="estimate-the-ate-by-tmle.html#cb81-16" tabindex="-1"></a><span class="do">## We define your own HAL algorithm that can run on both continuous and binary outcomes</span></span>
<span id="cb81-17"><a href="estimate-the-ate-by-tmle.html#cb81-17" tabindex="-1"></a>SL.hal9001.Qbar <span class="ot">&lt;-</span> <span class="cf">function</span> (Y, X, newX, family, obsWeights, id, <span class="at">max_degree =</span> <span class="dv">2</span>, </span>
<span id="cb81-18"><a href="estimate-the-ate-by-tmle.html#cb81-18" tabindex="-1"></a>                             <span class="at">smoothness_orders =</span> <span class="dv">1</span>, <span class="at">num_knots =</span> <span class="dv">5</span>, ...) {</span>
<span id="cb81-19"><a href="estimate-the-ate-by-tmle.html#cb81-19" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.matrix</span>(X)) </span>
<span id="cb81-20"><a href="estimate-the-ate-by-tmle.html#cb81-20" tabindex="-1"></a>    X <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(X)</span>
<span id="cb81-21"><a href="estimate-the-ate-by-tmle.html#cb81-21" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(newX) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.matrix</span>(newX)) </span>
<span id="cb81-22"><a href="estimate-the-ate-by-tmle.html#cb81-22" tabindex="-1"></a>    newX <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(newX)</span>
<span id="cb81-23"><a href="estimate-the-ate-by-tmle.html#cb81-23" tabindex="-1"></a>  </span>
<span id="cb81-24"><a href="estimate-the-ate-by-tmle.html#cb81-24" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(<span class="fu">unique</span>(Y)) <span class="sc">==</span> <span class="dv">2</span>) { <span class="co"># for binomial family</span></span>
<span id="cb81-25"><a href="estimate-the-ate-by-tmle.html#cb81-25" tabindex="-1"></a>    hal_fit <span class="ot">&lt;-</span> hal9001<span class="sc">::</span><span class="fu">fit_hal</span>(<span class="at">Y =</span> Y, <span class="at">X =</span> X, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, </span>
<span id="cb81-26"><a href="estimate-the-ate-by-tmle.html#cb81-26" tabindex="-1"></a>                                <span class="at">weights =</span> obsWeights, <span class="at">id =</span> id, <span class="at">max_degree =</span> max_degree, </span>
<span id="cb81-27"><a href="estimate-the-ate-by-tmle.html#cb81-27" tabindex="-1"></a>                                <span class="at">smoothness_orders =</span> smoothness_orders, <span class="at">num_knots =</span> num_knots, </span>
<span id="cb81-28"><a href="estimate-the-ate-by-tmle.html#cb81-28" tabindex="-1"></a>                                ...)</span>
<span id="cb81-29"><a href="estimate-the-ate-by-tmle.html#cb81-29" tabindex="-1"></a>  }</span>
<span id="cb81-30"><a href="estimate-the-ate-by-tmle.html#cb81-30" tabindex="-1"></a>  </span>
<span id="cb81-31"><a href="estimate-the-ate-by-tmle.html#cb81-31" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(<span class="fu">unique</span>(Y)) <span class="sc">&gt;</span> <span class="dv">2</span>) { <span class="co"># for quasibinomial family</span></span>
<span id="cb81-32"><a href="estimate-the-ate-by-tmle.html#cb81-32" tabindex="-1"></a>    hal_fit <span class="ot">&lt;-</span> hal9001<span class="sc">::</span><span class="fu">fit_hal</span>(<span class="at">Y =</span> Y, <span class="at">X =</span> X, <span class="at">family =</span> <span class="st">&quot;gaussian&quot;</span>, </span>
<span id="cb81-33"><a href="estimate-the-ate-by-tmle.html#cb81-33" tabindex="-1"></a>                                <span class="at">weights =</span> obsWeights, <span class="at">id =</span> id, <span class="at">max_degree =</span> max_degree, </span>
<span id="cb81-34"><a href="estimate-the-ate-by-tmle.html#cb81-34" tabindex="-1"></a>                                <span class="at">smoothness_orders =</span> smoothness_orders, <span class="at">num_knots =</span> num_knots, </span>
<span id="cb81-35"><a href="estimate-the-ate-by-tmle.html#cb81-35" tabindex="-1"></a>                                ...)</span>
<span id="cb81-36"><a href="estimate-the-ate-by-tmle.html#cb81-36" tabindex="-1"></a>  }</span>
<span id="cb81-37"><a href="estimate-the-ate-by-tmle.html#cb81-37" tabindex="-1"></a>  </span>
<span id="cb81-38"><a href="estimate-the-ate-by-tmle.html#cb81-38" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(newX)) {</span>
<span id="cb81-39"><a href="estimate-the-ate-by-tmle.html#cb81-39" tabindex="-1"></a>    pred <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">predict</span>(hal_fit, <span class="at">new_data =</span> newX)</span>
<span id="cb81-40"><a href="estimate-the-ate-by-tmle.html#cb81-40" tabindex="-1"></a>  }</span>
<span id="cb81-41"><a href="estimate-the-ate-by-tmle.html#cb81-41" tabindex="-1"></a>  <span class="cf">else</span> {</span>
<span id="cb81-42"><a href="estimate-the-ate-by-tmle.html#cb81-42" tabindex="-1"></a>    pred <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">predict</span>(hal_fit, <span class="at">new_data =</span> X)</span>
<span id="cb81-43"><a href="estimate-the-ate-by-tmle.html#cb81-43" tabindex="-1"></a>  }</span>
<span id="cb81-44"><a href="estimate-the-ate-by-tmle.html#cb81-44" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">object =</span> hal_fit)</span>
<span id="cb81-45"><a href="estimate-the-ate-by-tmle.html#cb81-45" tabindex="-1"></a>  <span class="fu">class</span>(fit) <span class="ot">&lt;-</span> <span class="st">&quot;SL.hal9001&quot;</span></span>
<span id="cb81-46"><a href="estimate-the-ate-by-tmle.html#cb81-46" tabindex="-1"></a>  out <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">pred =</span> pred, <span class="at">fit =</span> fit)</span>
<span id="cb81-47"><a href="estimate-the-ate-by-tmle.html#cb81-47" tabindex="-1"></a>  <span class="fu">return</span>(out)</span>
<span id="cb81-48"><a href="estimate-the-ate-by-tmle.html#cb81-48" tabindex="-1"></a>}</span>
<span id="cb81-49"><a href="estimate-the-ate-by-tmle.html#cb81-49" tabindex="-1"></a><span class="fu">environment</span>(SL.hal9001.Qbar) <span class="ot">&lt;-</span><span class="fu">asNamespace</span>(<span class="st">&quot;SuperLearner&quot;</span>)</span>
<span id="cb81-50"><a href="estimate-the-ate-by-tmle.html#cb81-50" tabindex="-1"></a></span>
<span id="cb81-51"><a href="estimate-the-ate-by-tmle.html#cb81-51" tabindex="-1"></a><span class="do">## the algorithms we would like to use can be specified separately for the Q and </span></span>
<span id="cb81-52"><a href="estimate-the-ate-by-tmle.html#cb81-52" tabindex="-1"></a><span class="co"># g functions</span></span>
<span id="cb81-53"><a href="estimate-the-ate-by-tmle.html#cb81-53" tabindex="-1"></a>SL.library <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">Q=</span><span class="fu">list</span>(<span class="st">&quot;SL.mean&quot;</span>, <span class="st">&quot;SL.glm&quot;</span>, <span class="fu">c</span>(<span class="st">&quot;SL.glm&quot;</span>, <span class="st">&quot;screen.corP&quot;</span>), </span>
<span id="cb81-54"><a href="estimate-the-ate-by-tmle.html#cb81-54" tabindex="-1"></a>                       <span class="st">&quot;SL.interaction.back&quot;</span>, <span class="st">&quot;SL.hal9001&quot;</span>),</span>
<span id="cb81-55"><a href="estimate-the-ate-by-tmle.html#cb81-55" tabindex="-1"></a>                   <span class="at">g=</span><span class="fu">list</span>(<span class="st">&quot;SL.mean&quot;</span>, <span class="st">&quot;SL.glm&quot;</span>, <span class="fu">c</span>(<span class="st">&quot;SL.glm&quot;</span>, <span class="st">&quot;screen.corP&quot;</span>), </span>
<span id="cb81-56"><a href="estimate-the-ate-by-tmle.html#cb81-56" tabindex="-1"></a>                       <span class="st">&quot;SL.interaction.back&quot;</span>, <span class="st">&quot;SL.hal9001&quot;</span>))</span>
<span id="cb81-57"><a href="estimate-the-ate-by-tmle.html#cb81-57" tabindex="-1"></a></span>
<span id="cb81-58"><a href="estimate-the-ate-by-tmle.html#cb81-58" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb81-59"><a href="estimate-the-ate-by-tmle.html#cb81-59" tabindex="-1"></a>Psi_ATE_tmle <span class="ot">&lt;-</span> <span class="fu">ltmle</span>(<span class="at">data =</span> data_ltmle,</span>
<span id="cb81-60"><a href="estimate-the-ate-by-tmle.html#cb81-60" tabindex="-1"></a>                      <span class="at">Anodes =</span> <span class="st">&quot;edu&quot;</span>,</span>
<span id="cb81-61"><a href="estimate-the-ate-by-tmle.html#cb81-61" tabindex="-1"></a>                      <span class="at">Ynodes =</span> <span class="st">&quot;death&quot;</span>,</span>
<span id="cb81-62"><a href="estimate-the-ate-by-tmle.html#cb81-62" tabindex="-1"></a>                      <span class="at">Qform =</span> Qform,</span>
<span id="cb81-63"><a href="estimate-the-ate-by-tmle.html#cb81-63" tabindex="-1"></a>                      <span class="at">gform =</span> gform,</span>
<span id="cb81-64"><a href="estimate-the-ate-by-tmle.html#cb81-64" tabindex="-1"></a>                      <span class="at">gbounds =</span> <span class="fu">c</span>(<span class="fl">0.01</span>, <span class="dv">1</span>),</span>
<span id="cb81-65"><a href="estimate-the-ate-by-tmle.html#cb81-65" tabindex="-1"></a>                      <span class="at">abar =</span> <span class="fu">list</span>(<span class="dv">1</span>,<span class="dv">0</span>), <span class="co"># vector of the counterfactual treatment</span></span>
<span id="cb81-66"><a href="estimate-the-ate-by-tmle.html#cb81-66" tabindex="-1"></a>                      <span class="at">SL.library =</span> SL.library,</span>
<span id="cb81-67"><a href="estimate-the-ate-by-tmle.html#cb81-67" tabindex="-1"></a>                      <span class="at">variance.method =</span> <span class="st">&quot;ic&quot;</span>)</span>
<span id="cb81-68"><a href="estimate-the-ate-by-tmle.html#cb81-68" tabindex="-1"></a><span class="co"># The estimation is more computer intensive</span></span>
<span id="cb81-69"><a href="estimate-the-ate-by-tmle.html#cb81-69" tabindex="-1"></a><span class="co"># The function give the ATE on the difference scale (as well, as RR and OR)</span></span>
<span id="cb81-70"><a href="estimate-the-ate-by-tmle.html#cb81-70" tabindex="-1"></a><span class="fu">summary</span>(Psi_ATE_tmle, <span class="at">estimator =</span> <span class="st">&quot;tmle&quot;</span>)</span></code></pre></div>
<pre><code>## Estimator:  tmle 
## Call:
## ltmle(data = data_ltmle, Anodes = &quot;edu&quot;, Ynodes = &quot;death&quot;, Qform = Qform, 
##     gform = gform, abar = list(1, 0), gbounds = c(0.01, 1), SL.library = SL.library, 
##     variance.method = &quot;ic&quot;)
## 
## Treatment Estimate:
##    Parameter Estimate:  0.33064 
##     Estimated Std Err:  0.0060897 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (0.3187, 0.34258) 
## 
## Control Estimate:
##    Parameter Estimate:  0.14418 
##     Estimated Std Err:  0.0056066 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (0.13319, 0.15517) 
## 
## Additive Treatment Effect:
##    Parameter Estimate:  0.18646 
##     Estimated Std Err:  0.0082369 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (0.17031, 0.2026) 
## 
## Relative Risk:
##    Parameter Estimate:  2.2932 
##   Est Std Err log(RR):  0.042862 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (2.1084, 2.4942) 
## 
## Odds Ratio:
##    Parameter Estimate:  2.932 
##   Est Std Err log(OR):  0.052886 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (2.6433, 3.2522)</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="estimate-the-ate-by-tmle.html#cb83-1" tabindex="-1"></a><span class="co"># Additive Treatment Effect:</span></span>
<span id="cb83-2"><a href="estimate-the-ate-by-tmle.html#cb83-2" tabindex="-1"></a><span class="co">#    Parameter Estimate:  0.18646 </span></span>
<span id="cb83-3"><a href="estimate-the-ate-by-tmle.html#cb83-3" tabindex="-1"></a><span class="co">#     Estimated Std Err:  0.0082369 </span></span>
<span id="cb83-4"><a href="estimate-the-ate-by-tmle.html#cb83-4" tabindex="-1"></a><span class="co">#               p-value:  &lt;2e-16 </span></span>
<span id="cb83-5"><a href="estimate-the-ate-by-tmle.html#cb83-5" tabindex="-1"></a><span class="co">#     95% Conf Interval: (0.17031, 0.2026) </span></span>
<span id="cb83-6"><a href="estimate-the-ate-by-tmle.html#cb83-6" tabindex="-1"></a>    </span>
<span id="cb83-7"><a href="estimate-the-ate-by-tmle.html#cb83-7" tabindex="-1"></a><span class="do">## We can see how the SuperLearner used the algorithms for the g function</span></span>
<span id="cb83-8"><a href="estimate-the-ate-by-tmle.html#cb83-8" tabindex="-1"></a><span class="co"># we see that the Risk is high for the bad model (SL.mean)</span></span>
<span id="cb83-9"><a href="estimate-the-ate-by-tmle.html#cb83-9" tabindex="-1"></a><span class="co"># and very similar for the other models</span></span>
<span id="cb83-10"><a href="estimate-the-ate-by-tmle.html#cb83-10" tabindex="-1"></a>Psi_ATE_tmle<span class="sc">$</span>fit<span class="sc">$</span>g[[<span class="dv">1</span>]]</span></code></pre></div>
<pre><code>## $edu
##                              Risk        Coef
## SL.mean_All             0.2409651 0.004074661
## SL.glm_All              0.2358587 0.000000000
## SL.glm_screen.corP      0.2358587 0.995925339
## SL.interaction.back_All 0.2358587 0.000000000
## SL.hal9001_All          0.2358824 0.000000000</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="estimate-the-ate-by-tmle.html#cb85-1" tabindex="-1"></a><span class="do">## We can see how the SuperLearner used the algorithms for the Q function</span></span>
<span id="cb85-2"><a href="estimate-the-ate-by-tmle.html#cb85-2" tabindex="-1"></a>Psi_ATE_tmle<span class="sc">$</span>fit<span class="sc">$</span>Q</span></code></pre></div>
<pre><code>## [[1]]
## [[1]]$death
##                              Risk      Coef
## SL.mean_All             0.1905554 0.0000000
## SL.glm_All              0.1775983 0.6619501
## SL.glm_screen.corP      0.1775983 0.0000000
## SL.interaction.back_All 0.1775983 0.0000000
## SL.hal9001_All          0.1776157 0.3380499
## 
## 
## [[2]]
## [[2]]$death
##                              Risk      Coef
## SL.mean_All             0.1905554 0.0000000
## SL.glm_All              0.1775983 0.6619501
## SL.glm_screen.corP      0.1775983 0.0000000
## SL.interaction.back_All 0.1775983 0.0000000
## SL.hal9001_All          0.1776157 0.3380499</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="estimate-the-ate-by-tmle.html#cb87-1" tabindex="-1"></a><span class="co"># The SuperLearner predicts the Q function using a mix between the glm and </span></span>
<span id="cb87-2"><a href="estimate-the-ate-by-tmle.html#cb87-2" tabindex="-1"></a><span class="co"># the HAL algorithm. </span></span>
<span id="cb87-3"><a href="estimate-the-ate-by-tmle.html#cb87-3" tabindex="-1"></a><span class="co"># However, the choice between the 2 SL.glm and SL.interaction.back </span></span>
<span id="cb87-4"><a href="estimate-the-ate-by-tmle.html#cb87-4" tabindex="-1"></a><span class="co"># was arbitrary: as we can see the Risk is exactly the same for the 3 </span></span>
<span id="cb87-5"><a href="estimate-the-ate-by-tmle.html#cb87-5" tabindex="-1"></a><span class="co"># algorithms. The final model from the step-by-step procedure and the glm after</span></span>
<span id="cb87-6"><a href="estimate-the-ate-by-tmle.html#cb87-6" tabindex="-1"></a><span class="co"># the screening procedure were probably the same &quot;main term&quot; glm.</span></span>
<span id="cb87-7"><a href="estimate-the-ate-by-tmle.html#cb87-7" tabindex="-1"></a></span>
<span id="cb87-8"><a href="estimate-the-ate-by-tmle.html#cb87-8" tabindex="-1"></a></span>
<span id="cb87-9"><a href="estimate-the-ate-by-tmle.html#cb87-9" tabindex="-1"></a><span class="do">## The `ltmle` package can also be used to estimate the effect of categorical </span></span>
<span id="cb87-10"><a href="estimate-the-ate-by-tmle.html#cb87-10" tabindex="-1"></a><span class="do">## exposures on continous outcomes</span></span>
<span id="cb87-11"><a href="estimate-the-ate-by-tmle.html#cb87-11" tabindex="-1"></a>Qform <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">score=</span><span class="st">&quot;Q.kplus1 ~ sex + low_par_edu + edu&quot;</span>)</span>
<span id="cb87-12"><a href="estimate-the-ate-by-tmle.html#cb87-12" tabindex="-1"></a>gform <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;edu ~ sex + low_par_edu&quot;</span>)</span>
<span id="cb87-13"><a href="estimate-the-ate-by-tmle.html#cb87-13" tabindex="-1"></a></span>
<span id="cb87-14"><a href="estimate-the-ate-by-tmle.html#cb87-14" tabindex="-1"></a>SL.library <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">Q=</span><span class="fu">c</span>(<span class="st">&quot;SL.mean&quot;</span>,<span class="st">&quot;SL.glm&quot;</span>,<span class="st">&quot;SL.interaction.back&quot;</span>, <span class="st">&quot;SL.hal9001.Qbar&quot;</span>),</span>
<span id="cb87-15"><a href="estimate-the-ate-by-tmle.html#cb87-15" tabindex="-1"></a>                   <span class="at">g=</span><span class="fu">c</span>(<span class="st">&quot;SL.mean&quot;</span>,<span class="st">&quot;SL.glm&quot;</span>,<span class="st">&quot;SL.interaction.back&quot;</span>, <span class="st">&quot;SL.hal9001&quot;</span>))</span>
<span id="cb87-16"><a href="estimate-the-ate-by-tmle.html#cb87-16" tabindex="-1"></a></span>
<span id="cb87-17"><a href="estimate-the-ate-by-tmle.html#cb87-17" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb87-18"><a href="estimate-the-ate-by-tmle.html#cb87-18" tabindex="-1"></a>Psi_ATE_tmle_score <span class="ot">&lt;-</span> <span class="fu">ltmle</span>(<span class="at">data =</span> <span class="fu">subset</span>(df, </span>
<span id="cb87-19"><a href="estimate-the-ate-by-tmle.html#cb87-19" tabindex="-1"></a>                                          <span class="at">select =</span> <span class="fu">c</span>(sex, low_par_edu,</span>
<span id="cb87-20"><a href="estimate-the-ate-by-tmle.html#cb87-20" tabindex="-1"></a>                                                     edu,</span>
<span id="cb87-21"><a href="estimate-the-ate-by-tmle.html#cb87-21" tabindex="-1"></a>                                                     score)),</span>
<span id="cb87-22"><a href="estimate-the-ate-by-tmle.html#cb87-22" tabindex="-1"></a>                      <span class="at">Anodes =</span> <span class="st">&quot;edu&quot;</span>,</span>
<span id="cb87-23"><a href="estimate-the-ate-by-tmle.html#cb87-23" tabindex="-1"></a>                      <span class="at">Ynodes =</span> <span class="st">&quot;score&quot;</span>,</span>
<span id="cb87-24"><a href="estimate-the-ate-by-tmle.html#cb87-24" tabindex="-1"></a>                      <span class="at">Qform =</span> Qform,</span>
<span id="cb87-25"><a href="estimate-the-ate-by-tmle.html#cb87-25" tabindex="-1"></a>                      <span class="at">gform =</span> gform,</span>
<span id="cb87-26"><a href="estimate-the-ate-by-tmle.html#cb87-26" tabindex="-1"></a>                      <span class="at">gbounds =</span> <span class="fu">c</span>(<span class="fl">0.01</span>, <span class="dv">1</span>),</span>
<span id="cb87-27"><a href="estimate-the-ate-by-tmle.html#cb87-27" tabindex="-1"></a>                      <span class="at">abar =</span> <span class="fu">list</span>(<span class="dv">1</span>,<span class="dv">0</span>), <span class="co"># vector of the counterfactual treatment </span></span>
<span id="cb87-28"><a href="estimate-the-ate-by-tmle.html#cb87-28" tabindex="-1"></a>                      <span class="at">SL.library =</span> SL.library,</span>
<span id="cb87-29"><a href="estimate-the-ate-by-tmle.html#cb87-29" tabindex="-1"></a>                      <span class="at">variance.method =</span> <span class="st">&quot;ic&quot;</span>)</span>
<span id="cb87-30"><a href="estimate-the-ate-by-tmle.html#cb87-30" tabindex="-1"></a><span class="fu">summary</span>(Psi_ATE_tmle_score, <span class="at">estimator =</span> <span class="st">&quot;tmle&quot;</span>)</span></code></pre></div>
<pre><code>## Estimator:  tmle 
## Call:
## ltmle(data = subset(df, select = c(sex, low_par_edu, edu, score)), 
##     Anodes = &quot;edu&quot;, Ynodes = &quot;score&quot;, Qform = Qform, gform = gform, 
##     abar = list(1, 0), gbounds = c(0.01, 1), SL.library = SL.library, 
##     variance.method = &quot;ic&quot;)
## 
## Treatment Estimate:
##    Parameter Estimate:  22.496 
##     Estimated Std Err:  0.25199 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (22.002, 22.989) 
## 
## Control Estimate:
##    Parameter Estimate:  42.256 
##     Estimated Std Err:  0.28487 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (41.698, 42.814) 
## 
## Additive Treatment Effect:
##    Parameter Estimate:  -19.76 
##     Estimated Std Err:  0.37746 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (-20.5, -19.021)</code></pre>
<p>On the difference scale, the TMLE estimation of the ATE from the <code>ltmle</code> package for death probability and quantitative score is +18.65% (95% CI=[17.03%, +20.26%]) and -19.76 [-20.5, -19.021] respectively.</p>
<p>Note that the <code>ltmle</code> package can also be used to calculate the IPTW estimation of the ATE and the CDE.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="estimate-the-ate-by-tmle.html#cb89-1" tabindex="-1"></a><span class="co"># using the output from the previous ltmle() procedure</span></span>
<span id="cb89-2"><a href="estimate-the-ate-by-tmle.html#cb89-2" tabindex="-1"></a><span class="fu">summary</span>(Psi_ATE_tmle, <span class="at">estimator =</span> <span class="st">&quot;iptw&quot;</span>)</span></code></pre></div>
<pre><code>## Estimator:  iptw 
## Call:
## ltmle(data = data_ltmle, Anodes = &quot;edu&quot;, Ynodes = &quot;death&quot;, Qform = Qform, 
##     gform = gform, abar = list(1, 0), gbounds = c(0.01, 1), SL.library = SL.library, 
##     variance.method = &quot;ic&quot;)
## 
## Treatment Estimate:
##    Parameter Estimate:  0.33069 
##     Estimated Std Err:  0.0061262 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (0.31868, 0.3427) 
## 
## Control Estimate:
##    Parameter Estimate:  0.14409 
##     Estimated Std Err:  0.0056297 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (0.13306, 0.15513) 
## 
## Additive Treatment Effect:
##    Parameter Estimate:  0.18659 
##     Estimated Std Err:  0.0083201 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (0.17029, 0.2029) 
## 
## Relative Risk:
##    Parameter Estimate:  2.295 
##   Est Std Err log(RR):  0.04324 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (2.1085, 2.4979) 
## 
## Odds Ratio:
##    Parameter Estimate:  2.9348 
##   Est Std Err log(OR):  0.053383 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (2.6432, 3.2585)</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="estimate-the-ate-by-tmle.html#cb91-1" tabindex="-1"></a><span class="co"># Additive Treatment Effect:</span></span>
<span id="cb91-2"><a href="estimate-the-ate-by-tmle.html#cb91-2" tabindex="-1"></a><span class="co">#    Parameter Estimate:  0.18659 </span></span>
<span id="cb91-3"><a href="estimate-the-ate-by-tmle.html#cb91-3" tabindex="-1"></a><span class="co">#     Estimated Std Err:  0.0083201 </span></span>
<span id="cb91-4"><a href="estimate-the-ate-by-tmle.html#cb91-4" tabindex="-1"></a><span class="co">#               p-value:  &lt;2e-16 </span></span>
<span id="cb91-5"><a href="estimate-the-ate-by-tmle.html#cb91-5" tabindex="-1"></a><span class="co">#     95% Conf Interval: (0.17029, 0.2029) </span></span>
<span id="cb91-6"><a href="estimate-the-ate-by-tmle.html#cb91-6" tabindex="-1"></a></span>
<span id="cb91-7"><a href="estimate-the-ate-by-tmle.html#cb91-7" tabindex="-1"></a><span class="fu">summary</span>(Psi_ATE_tmle_score, <span class="at">estimator =</span> <span class="st">&quot;iptw&quot;</span>)</span></code></pre></div>
<pre><code>## Estimator:  iptw 
## Call:
## ltmle(data = subset(df, select = c(sex, low_par_edu, edu, score)), 
##     Anodes = &quot;edu&quot;, Ynodes = &quot;score&quot;, Qform = Qform, gform = gform, 
##     abar = list(1, 0), gbounds = c(0.01, 1), SL.library = SL.library, 
##     variance.method = &quot;ic&quot;)
## 
## Treatment Estimate:
##    Parameter Estimate:  22.491 
##     Estimated Std Err:  0.25389 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (21.993, 22.989) 
## 
## Control Estimate:
##    Parameter Estimate:  42.254 
##     Estimated Std Err:  0.2873 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (41.691, 42.817) 
## 
## Additive Treatment Effect:
##    Parameter Estimate:  -19.763 
##     Estimated Std Err:  0.38341 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (-20.515, -19.012)</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="estimate-the-ate-by-tmle.html#cb93-1" tabindex="-1"></a><span class="co"># Additive Treatment Effect:</span></span>
<span id="cb93-2"><a href="estimate-the-ate-by-tmle.html#cb93-2" tabindex="-1"></a><span class="co">#    Parameter Estimate:  -19.763 </span></span>
<span id="cb93-3"><a href="estimate-the-ate-by-tmle.html#cb93-3" tabindex="-1"></a><span class="co">#     Estimated Std Err:  0.38341 </span></span>
<span id="cb93-4"><a href="estimate-the-ate-by-tmle.html#cb93-4" tabindex="-1"></a><span class="co">#               p-value:  &lt;2e-16 </span></span>
<span id="cb93-5"><a href="estimate-the-ate-by-tmle.html#cb93-5" tabindex="-1"></a><span class="co">#     95% Conf Interval: (-20.515, -19.012) </span></span></code></pre></div>
<p>On a difference scale, the IPTW estimation of the ATE from the <code>ltmle</code> package for death probability and the quantitative score is +18.66% (95% CI=[+17.03%, +20.29%]) and -19.76 [-20.52, -19.01], respectively.</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-vanderlaan_book2011" class="csl-entry">
Laan, Mark J. van der, and Sherri Rose. 2011. <em>Targeted Learning: Causal Inference for Observational and Experimental Data.</em> 1st ed. Springer Series in Statistics. New York, NY: Springer.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="applying-the-cmaverse.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="estimate-the-cde-using-the-ltmle-package.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": false,
    "twitter": false,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/benoitlepage/Inserm_workshop_282/03-ATE_by_tmle.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
