<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Estimate the CDE using the ltmle package | Inserm Workshop 282 - practical session</title>
  <meta name="description" content="Chapter 5 Estimate the CDE using the ltmle package | Inserm Workshop 282 - practical session" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Estimate the CDE using the ltmle package | Inserm Workshop 282 - practical session" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Chapter 5 Estimate the CDE using the ltmle package | Inserm Workshop 282 - practical session" />
  <meta name="github-repo" content="Inserm_workshop_282" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Estimate the CDE using the ltmle package | Inserm Workshop 282 - practical session" />
  
  <meta name="twitter:description" content="Chapter 5 Estimate the CDE using the ltmle package | Inserm Workshop 282 - practical session" />
  

<meta name="author" content="Benoît Lepage" />


<meta name="date" content="2025-10-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="estimate-the-ate-by-tmle.html"/>
<link rel="next" href="estimate-rnde-and-rnie-by-double-robust-estimators.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Inserm_workshop_282</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data-generating-system"><i class="fa fa-check"></i><b>1.1</b> Data generating system</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reminders---estimate-the-ate.html"><a href="reminders---estimate-the-ate.html"><i class="fa fa-check"></i><b>2</b> Reminders - Estimate the ATE</a>
<ul>
<li class="chapter" data-level="2.1" data-path="reminders---estimate-the-ate.html"><a href="reminders---estimate-the-ate.html#estimation-of-the-average-total-effect-ate-by-g-computation"><i class="fa fa-check"></i><b>2.1</b> Estimation of the Average Total Effect (ATE) by g-computation</a></li>
<li class="chapter" data-level="2.2" data-path="reminders---estimate-the-ate.html"><a href="reminders---estimate-the-ate.html#estimation-of-the-ate-by-iptw"><i class="fa fa-check"></i><b>2.2</b> Estimation of the ATE by IPTW</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="reminders---estimate-the-ate.html"><a href="reminders---estimate-the-ate.html#classic-horvitz-thompson-estimator"><i class="fa fa-check"></i><b>2.2.1</b> “Classic” Horvitz Thompson estimator</a></li>
<li class="chapter" data-level="2.2.2" data-path="reminders---estimate-the-ate.html"><a href="reminders---estimate-the-ate.html#stabilized-iptw-for-the-ate"><i class="fa fa-check"></i><b>2.2.2</b> Stabilized IPTW for the ATE</a></li>
<li class="chapter" data-level="2.2.3" data-path="reminders---estimate-the-ate.html"><a href="reminders---estimate-the-ate.html#using-an-msm-estimated-by-iptw"><i class="fa fa-check"></i><b>2.2.3</b> Using an MSM estimated by IPTW</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="applying-the-cmaverse.html"><a href="applying-the-cmaverse.html"><i class="fa fa-check"></i><b>3</b> Applying the CMAverse</a>
<ul>
<li class="chapter" data-level="3.1" data-path="applying-the-cmaverse.html"><a href="applying-the-cmaverse.html#estimation-by-parametric-g-computation"><i class="fa fa-check"></i><b>3.1</b> Estimation by “parametric” g-computation</a></li>
<li class="chapter" data-level="3.2" data-path="applying-the-cmaverse.html"><a href="applying-the-cmaverse.html#estimation-by-msm-estimated-by-iptw"><i class="fa fa-check"></i><b>3.2</b> Estimation by MSM estimated by IPTW</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="estimate-the-ate-by-tmle.html"><a href="estimate-the-ate-by-tmle.html"><i class="fa fa-check"></i><b>4</b> Estimate the ATE by TMLE</a>
<ul>
<li class="chapter" data-level="4.1" data-path="estimate-the-ate-by-tmle.html"><a href="estimate-the-ate-by-tmle.html#tmle-for-the-ate"><i class="fa fa-check"></i><b>4.1</b> TMLE for the ATE</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html"><i class="fa fa-check"></i><b>5</b> Estimate the CDE using the <code>ltmle</code> package</a>
<ul>
<li class="chapter" data-level="5.1" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#ChapGcomp-CDE-ICE"><i class="fa fa-check"></i><b>5.1</b> G-computation by iterative conditional expectation</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#algorithm-and-manual-calculation"><i class="fa fa-check"></i><b>5.1.1</b> Algorithm and manual calculation</a></li>
<li class="chapter" data-level="5.1.2" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#g-computation-by-ice-using-the-ltmle-package"><i class="fa fa-check"></i><b>5.1.2</b> G-computation by ICE using the <code>ltmle</code> package</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#iptw-estimator-of-the-cde"><i class="fa fa-check"></i><b>5.2</b> IPTW estimator of the CDE</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#estimation-of-the-msm-coefficients-by-iptw"><i class="fa fa-check"></i><b>5.2.1</b> Estimation of the MSM coefficients by IPTW</a></li>
<li class="chapter" data-level="5.2.2" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#iptw-estmation-using-the-ltmle-package"><i class="fa fa-check"></i><b>5.2.2</b> IPTW estmation using the ltmle package</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#tmle-estimator-of-the-cde"><i class="fa fa-check"></i><b>5.3</b> TMLE estimator of the CDE</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#for-binary-outcomes"><i class="fa fa-check"></i><b>5.3.1</b> For binary outcomes</a></li>
<li class="chapter" data-level="5.3.2" data-path="estimate-the-cde-using-the-ltmle-package.html"><a href="estimate-the-cde-using-the-ltmle-package.html#for-continuous-outcomes"><i class="fa fa-check"></i><b>5.3.2</b> For continuous outcomes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="estimate-rnde-and-rnie-by-double-robust-estimators.html"><a href="estimate-rnde-and-rnie-by-double-robust-estimators.html"><i class="fa fa-check"></i><b>6</b> Estimate rNDE and rNIE by double robust estimators</a>
<ul>
<li class="chapter" data-level="6.1" data-path="estimate-rnde-and-rnie-by-double-robust-estimators.html"><a href="estimate-rnde-and-rnie-by-double-robust-estimators.html#g-computation-algorithm-to-compute-randomized-natural-direct-and-indirect-effects"><i class="fa fa-check"></i><b>6.1</b> G-computation algorithm to compute randomized Natural Direct and Indirect effects</a></li>
<li class="chapter" data-level="6.2" data-path="estimate-rnde-and-rnie-by-double-robust-estimators.html"><a href="estimate-rnde-and-rnie-by-double-robust-estimators.html#packages-to-get-double-robust-estimations"><i class="fa fa-check"></i><b>6.2</b> Packages to get double robust estimations</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ltmle-package-with-interval-censored-survival-data.html"><a href="ltmle-package-with-interval-censored-survival-data.html"><i class="fa fa-check"></i><b>7</b> <code>ltmle</code> package with interval censored survival data</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ltmle-package-with-interval-censored-survival-data.html"><a href="ltmle-package-with-interval-censored-survival-data.html#setting"><i class="fa fa-check"></i><b>7.1</b> Setting</a></li>
<li class="chapter" data-level="7.2" data-path="ltmle-package-with-interval-censored-survival-data.html"><a href="ltmle-package-with-interval-censored-survival-data.html#data-generating-function"><i class="fa fa-check"></i><b>7.2</b> Data generating function</a></li>
<li class="chapter" data-level="7.3" data-path="ltmle-package-with-interval-censored-survival-data.html"><a href="ltmle-package-with-interval-censored-survival-data.html#inspect-the-data-generated"><i class="fa fa-check"></i><b>7.3</b> Inspect the data generated</a></li>
<li class="chapter" data-level="7.4" data-path="ltmle-package-with-interval-censored-survival-data.html"><a href="ltmle-package-with-interval-censored-survival-data.html#estimate-the-controlled-direct-effect"><i class="fa fa-check"></i><b>7.4</b> Estimate the controlled direct effect</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Inserm Workshop 282 - practical session</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estimate-the-cde-using-the-ltmle-package" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Chapter 5</span> Estimate the CDE using the <code>ltmle</code> package<a href="estimate-the-cde-using-the-ltmle-package.html#estimate-the-cde-using-the-ltmle-package" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The ltmle package can be used to estimate controlled direct effects by:</p>
<ul>
<li>g-computation by iterative conditional expectation (ICE),</li>
<li>IPTW,</li>
<li>or TMLE.</li>
</ul>
<div id="ChapGcomp-CDE-ICE" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> G-computation by iterative conditional expectation<a href="estimate-the-cde-using-the-ltmle-package.html#ChapGcomp-CDE-ICE" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="algorithm-and-manual-calculation" class="section level3 hasAnchor" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Algorithm and manual calculation<a href="estimate-the-cde-using-the-ltmle-package.html#algorithm-and-manual-calculation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The following steps describe the implementation of the g-computation estimator by iterative conditional expectation (ICE) for the component <span class="math inline">\(\mathbb{E}(Y_{A=a^\prime,M=m})\)</span> used in the definition of CDE <span class="math inline">\(\Psi^{\text{CDE}_m} = \mathbb{E}(Y_{A=1,M=m}) - \mathbb{E}(Y_{A=0,M=m})\)</span>. Interestingly, there is no need to estimate or simulate <span class="math inline">\(L(1)\)</span> density with this method.</p>
<ol style="list-style-type: decimal">
<li><p>Fit a logistic or a linear regression of the final outcome, conditional on the exposure <span class="math inline">\(A\)</span>, the mediator <span class="math inline">\(M\)</span> and all the parents of <span class="math inline">\(Y\)</span> preceding <span class="math inline">\(M\)</span>, to estimate <span class="math inline">\(\overline{Q}_{L(2)} = \mathbb{E}(Y \mid L(0),A,L(1),M)\)</span>;</p></li>
<li><p>Use this estimate to predict an outcome for each subject <span class="math inline">\(\hat{\overline{Q}}_{L(2)}(A=a^\prime,M=m)_i\)</span>, by evaluating the regression fit <span class="math inline">\(\overline{Q}_{L(2)}\)</span> at the chosen value for the exposure <span class="math inline">\(A=a^\prime\)</span> and the mediator <span class="math inline">\(M=m\)</span>;</p></li>
<li><p>Fit a quasibinomial or a linear regression of the predicted values <span class="math inline">\(\hat{\overline{Q}}_{L(2)}(A=a^\prime,M=m)_i\)</span> conditional on the exposure <span class="math inline">\(A\)</span> and baseline confounders <span class="math inline">\(L(0)\)</span> to estimate <span class="math inline">\(\overline{Q}_{L(1)} = \mathbb{E}\left(\hat{\overline{Q}}_{L(2)}(A=a^\prime,M=m) \middle| L(0),A\right)\)</span>;</p></li>
<li><p>Use this estimate to predict the outcome <span class="math inline">\(\hat{\overline{Q}}_{L(1)}(A=a^\prime)_i\)</span> for each subject, by evaluating the regression fit <span class="math inline">\(\overline{Q}_{L(1)}\)</span> at <span class="math inline">\(A=a^\prime\)</span>;</p></li>
<li><p>Use the sample mean to estimate <span class="math inline">\(\Psi^{\text{CDE}_m}_{\text{gcomp}}\)</span>
<span class="math display">\[\begin{equation}
\hat{\Psi}^{\text{CDE}_m}_{\text{gcomp}} = \frac{1}{n} \sum_{i=1}^n \left[ \hat{\overline{Q}}_{L(1)}(A=1)_i - \hat{\overline{Q}}_{L(1)}(A=0)_i \right]
\end{equation}\]</span></p></li>
</ol>
<p>Note that G-computation by iterative expectation is preferable if the set of intermediate confounders <span class="math inline">\(L(1)\)</span> is high-dimensional as we only need to fit 2 models by counterfactual scenario (for a whole set of <span class="math inline">\(L(1)\)</span> variables) in the procedure described below, whereas at least 1 model by <span class="math inline">\(L(1)\)</span> variable and the model of the outcome are needed with parametric g-computation.</p>
<p>In the following example, we will focus on the estimand <span class="math inline">\(CDE(M=0) = \mathbb{E}(Y_{A=1,M=0}) - \mathbb{E}(Y_{A=0,M=0})\)</span>.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-1" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb94-2"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">&quot;data/df.csv&quot;</span>)</span>
<span id="cb94-3"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-3" tabindex="-1"></a></span>
<span id="cb94-4"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-4" tabindex="-1"></a><span class="do">## 1) Regress the outcome on L0, A, L1 and M (and the A*M interaction if appropriate)</span></span>
<span id="cb94-5"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-5" tabindex="-1"></a>death_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(death <span class="sc">~</span> sex <span class="sc">+</span> low_par_edu <span class="sc">+</span> edu <span class="sc">+</span> phys <span class="sc">+</span> occupation <span class="sc">+</span></span>
<span id="cb94-6"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-6" tabindex="-1"></a>                     smoking <span class="sc">+</span> edu<span class="sc">:</span>smoking,</span>
<span id="cb94-7"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-7" tabindex="-1"></a>                   <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="at">data =</span> df)</span>
<span id="cb94-8"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-8" tabindex="-1"></a>                       </span>
<span id="cb94-9"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-9" tabindex="-1"></a>score_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(score <span class="sc">~</span> sex <span class="sc">+</span> low_par_edu <span class="sc">+</span> edu <span class="sc">+</span> phys <span class="sc">+</span> occupation <span class="sc">+</span></span>
<span id="cb94-10"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-10" tabindex="-1"></a>                     smoking <span class="sc">+</span> edu<span class="sc">:</span>smoking,</span>
<span id="cb94-11"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-11" tabindex="-1"></a>                   <span class="at">family =</span> <span class="st">&quot;gaussian&quot;</span>, <span class="at">data =</span> df)</span>
<span id="cb94-12"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-12" tabindex="-1"></a></span>
<span id="cb94-13"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-13" tabindex="-1"></a><span class="do">## 2) Generate predicted values by evaluating the regression setting the exposure</span></span>
<span id="cb94-14"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-14" tabindex="-1"></a><span class="do">##    and the mediator at exposure history of interest:</span></span>
<span id="cb94-15"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-15" tabindex="-1"></a><span class="do">##    {A=1,M=0},{A=0,M=0}</span></span>
<span id="cb94-16"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-16" tabindex="-1"></a>data_Ais0_Mis0 <span class="ot">&lt;-</span> data_Ais1_Mis0 <span class="ot">&lt;-</span> df</span>
<span id="cb94-17"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-17" tabindex="-1"></a></span>
<span id="cb94-18"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-18" tabindex="-1"></a>data_Ais0_Mis0<span class="sc">$</span>edu <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb94-19"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-19" tabindex="-1"></a>data_Ais0_Mis0<span class="sc">$</span>smoking <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb94-20"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-20" tabindex="-1"></a></span>
<span id="cb94-21"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-21" tabindex="-1"></a>data_Ais1_Mis0<span class="sc">$</span>edu <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb94-22"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-22" tabindex="-1"></a>data_Ais1_Mis0<span class="sc">$</span>smoking <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb94-23"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-23" tabindex="-1"></a></span>
<span id="cb94-24"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-24" tabindex="-1"></a>Q_L2_death_A0M0 <span class="ot">&lt;-</span> <span class="fu">predict</span>(death_model, </span>
<span id="cb94-25"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-25" tabindex="-1"></a>                           <span class="at">newdata =</span> data_Ais0_Mis0, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb94-26"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-26" tabindex="-1"></a>Q_L2_death_A1M0 <span class="ot">&lt;-</span> <span class="fu">predict</span>(death_model, </span>
<span id="cb94-27"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-27" tabindex="-1"></a>                           <span class="at">newdata =</span> data_Ais1_Mis0, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb94-28"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-28" tabindex="-1"></a></span>
<span id="cb94-29"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-29" tabindex="-1"></a>Q_L2_score_A0M0 <span class="ot">&lt;-</span> <span class="fu">predict</span>(score_model, </span>
<span id="cb94-30"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-30" tabindex="-1"></a>                           <span class="at">newdata =</span> data_Ais0_Mis0, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb94-31"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-31" tabindex="-1"></a>Q_L2_score_A1M0 <span class="ot">&lt;-</span> <span class="fu">predict</span>(score_model, </span>
<span id="cb94-32"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-32" tabindex="-1"></a>                           <span class="at">newdata =</span> data_Ais1_Mis0, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb94-33"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-33" tabindex="-1"></a></span>
<span id="cb94-34"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-34" tabindex="-1"></a><span class="do">## 3) Regress the predicted values conditional on the exposure A</span></span>
<span id="cb94-35"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-35" tabindex="-1"></a><span class="do">##    and baseline confounders L(0)</span></span>
<span id="cb94-36"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-36" tabindex="-1"></a>L1_death_A0M0_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(Q_L2_death_A0M0 <span class="sc">~</span> sex <span class="sc">+</span> low_par_edu <span class="sc">+</span> edu,</span>
<span id="cb94-37"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-37" tabindex="-1"></a>                           <span class="at">family =</span> <span class="st">&quot;quasibinomial&quot;</span>, <span class="at">data =</span> df)</span>
<span id="cb94-38"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-38" tabindex="-1"></a>L1_death_A1M0_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(Q_L2_death_A1M0 <span class="sc">~</span> sex <span class="sc">+</span> low_par_edu <span class="sc">+</span> edu,</span>
<span id="cb94-39"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-39" tabindex="-1"></a>                           <span class="at">family =</span> <span class="st">&quot;quasibinomial&quot;</span>, <span class="at">data =</span> df)</span>
<span id="cb94-40"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-40" tabindex="-1"></a></span>
<span id="cb94-41"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-41" tabindex="-1"></a>L1_score_A0M0_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(Q_L2_score_A0M0 <span class="sc">~</span> sex <span class="sc">+</span> low_par_edu <span class="sc">+</span> edu,</span>
<span id="cb94-42"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-42" tabindex="-1"></a>                           <span class="at">family =</span> <span class="st">&quot;gaussian&quot;</span>, <span class="at">data =</span> df)</span>
<span id="cb94-43"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-43" tabindex="-1"></a>L1_score_A1M0_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(Q_L2_score_A1M0 <span class="sc">~</span> sex <span class="sc">+</span> low_par_edu <span class="sc">+</span> edu,</span>
<span id="cb94-44"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-44" tabindex="-1"></a>                           <span class="at">family =</span> <span class="st">&quot;gaussian&quot;</span>, <span class="at">data =</span> df)</span>
<span id="cb94-45"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-45" tabindex="-1"></a></span>
<span id="cb94-46"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-46" tabindex="-1"></a><span class="do">## 4) generate predicted values by evaluating the regression at exposure </span></span>
<span id="cb94-47"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-47" tabindex="-1"></a><span class="do">##    of interest: {A=1} &amp; {A=0}</span></span>
<span id="cb94-48"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-48" tabindex="-1"></a>Q_L1_death_A0M0 <span class="ot">&lt;-</span> <span class="fu">predict</span>(L1_death_A0M0_model, </span>
<span id="cb94-49"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-49" tabindex="-1"></a>                           <span class="at">newdata =</span> data_Ais0_Mis0, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb94-50"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-50" tabindex="-1"></a>Q_L1_death_A1M0 <span class="ot">&lt;-</span> <span class="fu">predict</span>(L1_death_A1M0_model, </span>
<span id="cb94-51"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-51" tabindex="-1"></a>                           <span class="at">newdata =</span> data_Ais1_Mis0, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb94-52"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-52" tabindex="-1"></a></span>
<span id="cb94-53"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-53" tabindex="-1"></a>Q_L1_score_A0M0 <span class="ot">&lt;-</span> <span class="fu">predict</span>(L1_score_A0M0_model, </span>
<span id="cb94-54"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-54" tabindex="-1"></a>                           <span class="at">newdata =</span> data_Ais0_Mis0, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb94-55"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-55" tabindex="-1"></a>Q_L1_score_A1M0 <span class="ot">&lt;-</span> <span class="fu">predict</span>(L1_score_A1M0_model, </span>
<span id="cb94-56"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-56" tabindex="-1"></a>                           <span class="at">newdata =</span> data_Ais1_Mis0, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb94-57"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-57" tabindex="-1"></a></span>
<span id="cb94-58"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-58" tabindex="-1"></a><span class="do">## 5) Take empirical mean of final predicted outcomes to estimate CDE</span></span>
<span id="cb94-59"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-59" tabindex="-1"></a><span class="co"># CDE setting M=0</span></span>
<span id="cb94-60"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-60" tabindex="-1"></a>CDE_death_m0_gcomp_ice <span class="ot">&lt;-</span> <span class="fu">mean</span>(Q_L1_death_A1M0) <span class="sc">-</span> <span class="fu">mean</span>(Q_L1_death_A0M0)</span>
<span id="cb94-61"><a href="estimate-the-cde-using-the-ltmle-package.html#cb94-61" tabindex="-1"></a>CDE_death_m0_gcomp_ice</span></code></pre></div>
<pre><code>## [1] 0.07202748</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb96-1" tabindex="-1"></a>CDE_score_m0_gcomp_ice <span class="ot">&lt;-</span> <span class="fu">mean</span>(Q_L1_score_A1M0) <span class="sc">-</span> <span class="fu">mean</span>(Q_L1_score_A0M0)</span>
<span id="cb96-2"><a href="estimate-the-cde-using-the-ltmle-package.html#cb96-2" tabindex="-1"></a>CDE_score_m0_gcomp_ice</span></code></pre></div>
<pre><code>## [1] -12.04431</code></pre>
<p>Applying g-computation by iterative expectation, the CDE setting the mediator to 0 is +7.20% for death and -12.04 for the quantitative score.</p>
<p>95% confidence intervals can be estimated by bootstrap methods.</p>
</div>
<div id="g-computation-by-ice-using-the-ltmle-package" class="section level3 hasAnchor" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> G-computation by ICE using the <code>ltmle</code> package<a href="estimate-the-cde-using-the-ltmle-package.html#g-computation-by-ice-using-the-ltmle-package" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <code>ltmle</code> package can be used to estimate Controlled Direct Effects by g-computation, as shown below.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-1" tabindex="-1"></a><span class="fu">library</span>(ltmle)</span>
<span id="cb98-2"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-2" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb98-3"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-3" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">&quot;data/df.csv&quot;</span>)</span>
<span id="cb98-4"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-4" tabindex="-1"></a></span>
<span id="cb98-5"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-5" tabindex="-1"></a><span class="co"># the data set should be composed of continuous or binary variables,</span></span>
<span id="cb98-6"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-6" tabindex="-1"></a><span class="co"># ordered following the cause-effect sequence of each variables.</span></span>
<span id="cb98-7"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-7" tabindex="-1"></a><span class="co"># Note that within a set of exposures or intermediate confounders measured at a</span></span>
<span id="cb98-8"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-8" tabindex="-1"></a><span class="co"># single discrete time t, any causal sequence can be applied (for example,</span></span>
<span id="cb98-9"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-9" tabindex="-1"></a><span class="co"># with several L1 variable, it can be {L1.1, L1.2, L1.3} or {L1.2,L1.3,L1.1},</span></span>
<span id="cb98-10"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-10" tabindex="-1"></a><span class="co"># without any consequences on the estimation.</span></span>
<span id="cb98-11"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-11" tabindex="-1"></a>df_death <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(X, subjid, score))</span>
<span id="cb98-12"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-12" tabindex="-1"></a>df_score <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(X, subjid, death))</span>
<span id="cb98-13"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-13" tabindex="-1"></a></span>
<span id="cb98-14"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-14" tabindex="-1"></a><span class="do">## 1) Define Q formulas (Qbar_L1 and Qbar_Y functions)</span></span>
<span id="cb98-15"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-15" tabindex="-1"></a>Q_formulas_death <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">phys =</span> <span class="st">&quot;Q.kplus1 ~ sex + low_par_edu + edu&quot;</span>,</span>
<span id="cb98-16"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-16" tabindex="-1"></a>                      <span class="at">death =</span> <span class="st">&quot;Q.kplus1 ~ sex + low_par_edu + phys + occupation +</span></span>
<span id="cb98-17"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-17" tabindex="-1"></a><span class="st">                               edu * smoking&quot;</span>) <span class="co"># add interaction</span></span>
<span id="cb98-18"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-18" tabindex="-1"></a>Q_formulas_score <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">phys =</span> <span class="st">&quot;Q.kplus1 ~ sex + low_par_edu + edu&quot;</span>,</span>
<span id="cb98-19"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-19" tabindex="-1"></a>                    <span class="at">score =</span> <span class="st">&quot;Q.kplus1 ~ sex + low_par_edu + phys + occupation +</span></span>
<span id="cb98-20"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-20" tabindex="-1"></a><span class="st">                             edu * smoking&quot;</span>) <span class="co"># add interaction</span></span>
<span id="cb98-21"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-21" tabindex="-1"></a><span class="do">## 2) Define g formulas (needed for the ltmle package) but they are not used</span></span>
<span id="cb98-22"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-22" tabindex="-1"></a><span class="do">##    with the g-computation estimator</span></span>
<span id="cb98-23"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-23" tabindex="-1"></a>g_formulas <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;edu ~ sex + low_par_edu&quot;</span>, </span>
<span id="cb98-24"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-24" tabindex="-1"></a>                <span class="st">&quot;smoking ~ sex + low_par_edu + edu + phys + occupation&quot;</span>)</span>
<span id="cb98-25"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-25" tabindex="-1"></a></span>
<span id="cb98-26"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-26" tabindex="-1"></a><span class="do">## 3) Use the ltmle() function</span></span>
<span id="cb98-27"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-27" tabindex="-1"></a><span class="co"># arguments:</span></span>
<span id="cb98-28"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-28" tabindex="-1"></a><span class="co">#  - Anodes: indicate the exposure and the mediator variables</span></span>
<span id="cb98-29"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-29" tabindex="-1"></a><span class="co">#  - Lnodes: indicate the intermediate confounders (+/- baseline confounders)</span></span>
<span id="cb98-30"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-30" tabindex="-1"></a><span class="co">#  - Cnodes: censoring nodes, useless in our example</span></span>
<span id="cb98-31"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-31" tabindex="-1"></a><span class="co">#  - Ynodes: outcome variable</span></span>
<span id="cb98-32"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-32" tabindex="-1"></a><span class="co">#  - survivalOutcome = FALSE in our example</span></span>
<span id="cb98-33"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-33" tabindex="-1"></a><span class="co">#  - abar: list of the two values used to define counterfactual outcomes</span></span>
<span id="cb98-34"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-34" tabindex="-1"></a><span class="co">#          for the contrast of interest. For example, setting M=0,</span></span>
<span id="cb98-35"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-35" tabindex="-1"></a><span class="co">#          CDE(M=0) = E(Y_{A=1,M=0}) - E(Y_{A=0,M=0})</span></span>
<span id="cb98-36"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-36" tabindex="-1"></a><span class="co">#  - rule: to define dynamic rules (useless in our example)</span></span>
<span id="cb98-37"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-37" tabindex="-1"></a><span class="co">#  - gbounds = c(0.01, 1) by default. This parameter is not used with g-computation</span></span>
<span id="cb98-38"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-38" tabindex="-1"></a><span class="co">#  - Yrange = NULL, can be used to define range (min,max) for continuous outcomes</span></span>
<span id="cb98-39"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-39" tabindex="-1"></a><span class="co">#  - SL.library = &quot;glm&quot;,  will apply main terms glm models.</span></span>
<span id="cb98-40"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-40" tabindex="-1"></a><span class="co">#                 The argument can be used to specify SuperLearner libraries.</span></span>
<span id="cb98-41"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-41" tabindex="-1"></a><span class="co">#                 However, simple glm models might be preferable as data.adaptive</span></span>
<span id="cb98-42"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-42" tabindex="-1"></a><span class="co">#                 algorithms rely on cross-validation, which is difficult and long to</span></span>
<span id="cb98-43"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-43" tabindex="-1"></a><span class="co">#                 implement with the bootstrap procedure needed for 95% confidence</span></span>
<span id="cb98-44"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-44" tabindex="-1"></a><span class="co">#                 intervals</span></span>
<span id="cb98-45"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-45" tabindex="-1"></a><span class="co">#  - stratify = FALSE by default. If TRUE, glm estimations are stratified for</span></span>
<span id="cb98-46"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-46" tabindex="-1"></a><span class="co">#               each counterfactual scenario defined in abar.</span></span>
<span id="cb98-47"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-47" tabindex="-1"></a><span class="co">#  - estimate.time = FALSE. If TRUE, print a rough estimate of computation time</span></span>
<span id="cb98-48"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-48" tabindex="-1"></a><span class="co">#  - iptw.only = FALSE, useless with g-computation</span></span>
<span id="cb98-49"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-49" tabindex="-1"></a><span class="co">#  - variance.method = &quot;ic&quot;, computation is faster than with &quot;tmle&quot; which</span></span>
<span id="cb98-50"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-50" tabindex="-1"></a><span class="co">#                       is useless with g-comp: variance estimates rely on</span></span>
<span id="cb98-51"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-51" tabindex="-1"></a><span class="co">#                       influence curves which cannot be used with g-comp because</span></span>
<span id="cb98-52"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-52" tabindex="-1"></a><span class="co">#                       g-computation is not a asymptotically efficient estimator.</span></span>
<span id="cb98-53"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-53" tabindex="-1"></a><span class="co">#  - observation.weights = NULL, can be used to specify individual weights</span></span>
<span id="cb98-54"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-54" tabindex="-1"></a><span class="co">#  - id = subject identifiers, useful in case of clustered structure in the data</span></span>
<span id="cb98-55"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-55" tabindex="-1"></a></span>
<span id="cb98-56"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-56" tabindex="-1"></a><span class="do">## With a binary outcome, CDE(M=1) = P(Y_{A=1,M=0} = 1) - P(Y_{A=0,M=0} = 1)</span></span>
<span id="cb98-57"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-57" tabindex="-1"></a>ltmle_gcomp_CDE_M0 <span class="ot">&lt;-</span> <span class="fu">ltmle</span>(<span class="at">data =</span> df_death,</span>
<span id="cb98-58"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-58" tabindex="-1"></a>                            <span class="at">Anodes =</span> <span class="fu">c</span>(<span class="st">&quot;edu&quot;</span>, <span class="st">&quot;smoking&quot;</span>),</span>
<span id="cb98-59"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-59" tabindex="-1"></a>                            <span class="at">Lnodes =</span> <span class="fu">c</span>(<span class="st">&quot;phys&quot;</span>, <span class="st">&quot;occupation&quot;</span>),</span>
<span id="cb98-60"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-60" tabindex="-1"></a>                            <span class="at">Ynodes =</span> <span class="fu">c</span>(<span class="st">&quot;death&quot;</span>), <span class="co"># binary outcome</span></span>
<span id="cb98-61"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-61" tabindex="-1"></a>                            <span class="at">survivalOutcome =</span> <span class="cn">FALSE</span>,</span>
<span id="cb98-62"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-62" tabindex="-1"></a>                            <span class="at">Qform =</span> Q_formulas_death, <span class="co"># Q formulas</span></span>
<span id="cb98-63"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-63" tabindex="-1"></a>                            <span class="at">gform =</span> g_formulas, <span class="co"># g formulas</span></span>
<span id="cb98-64"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-64" tabindex="-1"></a>                            <span class="at">abar =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>),</span>
<span id="cb98-65"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-65" tabindex="-1"></a>                                        <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)), <span class="co"># EY_{A=1,M=0} vs EY_{A=0,M=0}</span></span>
<span id="cb98-66"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-66" tabindex="-1"></a>                            <span class="at">rule =</span> <span class="cn">NULL</span>,</span>
<span id="cb98-67"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-67" tabindex="-1"></a>                            <span class="at">gbounds =</span> <span class="fu">c</span>(<span class="fl">0.01</span>, <span class="dv">1</span>), <span class="co"># truncation of g, by default</span></span>
<span id="cb98-68"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-68" tabindex="-1"></a>                            <span class="at">Yrange =</span> <span class="cn">NULL</span>,</span>
<span id="cb98-69"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-69" tabindex="-1"></a>                            <span class="at">deterministic.g.function =</span> <span class="cn">NULL</span>,</span>
<span id="cb98-70"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-70" tabindex="-1"></a>                            <span class="at">stratify =</span> <span class="cn">FALSE</span>,</span>
<span id="cb98-71"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-71" tabindex="-1"></a>                            <span class="at">SL.library =</span> <span class="st">&quot;glm&quot;</span>,</span>
<span id="cb98-72"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-72" tabindex="-1"></a>                            <span class="at">SL.cvControl =</span> <span class="fu">list</span>(),</span>
<span id="cb98-73"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-73" tabindex="-1"></a>                            <span class="at">estimate.time =</span> <span class="cn">FALSE</span>,</span>
<span id="cb98-74"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-74" tabindex="-1"></a>                            <span class="at">gcomp =</span> <span class="cn">TRUE</span>, <span class="co"># should be TRUE for g-computation</span></span>
<span id="cb98-75"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-75" tabindex="-1"></a>                            <span class="at">iptw.only =</span> <span class="cn">FALSE</span>,</span>
<span id="cb98-76"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-76" tabindex="-1"></a>                            <span class="at">deterministic.Q.function =</span> <span class="cn">NULL</span>,</span>
<span id="cb98-77"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-77" tabindex="-1"></a>                            <span class="at">variance.method =</span> <span class="st">&quot;ic&quot;</span>,</span>
<span id="cb98-78"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-78" tabindex="-1"></a>                            <span class="at">observation.weights =</span> <span class="cn">NULL</span>,</span>
<span id="cb98-79"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-79" tabindex="-1"></a>                            <span class="at">id =</span> <span class="cn">NULL</span>)</span>
<span id="cb98-80"><a href="estimate-the-cde-using-the-ltmle-package.html#cb98-80" tabindex="-1"></a><span class="fu">summary</span>(ltmle_gcomp_CDE_M0)</span></code></pre></div>
<pre><code>## Estimator:  gcomp 
## Warning: inference for gcomp is not accurate! It is based on TMLE influence curves.
## Call:
## ltmle(data = df_death, Anodes = c(&quot;edu&quot;, &quot;smoking&quot;), Lnodes = c(&quot;phys&quot;, 
##     &quot;occupation&quot;), Ynodes = c(&quot;death&quot;), survivalOutcome = FALSE, 
##     Qform = Q_formulas_death, gform = g_formulas, abar = list(c(1, 
##         0), c(0, 0)), rule = NULL, gbounds = c(0.01, 1), Yrange = NULL, 
##     deterministic.g.function = NULL, stratify = FALSE, SL.library = &quot;glm&quot;, 
##     SL.cvControl = list(), estimate.time = FALSE, gcomp = TRUE, 
##     iptw.only = FALSE, deterministic.Q.function = NULL, variance.method = &quot;ic&quot;, 
##     observation.weights = NULL, id = NULL)
## 
## Treatment Estimate:
##    Parameter Estimate:  0.15656 
##     Estimated Std Err:  0.0085093 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (0.13988, 0.17324) 
## 
## Control Estimate:
##    Parameter Estimate:  0.084535 
##     Estimated Std Err:  0.0063349 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (0.072118, 0.096951) 
## 
## Additive Treatment Effect:
##    Parameter Estimate:  0.072027 
##     Estimated Std Err:  0.010602 
##               p-value:  1.0947e-11 
##     95% Conf Interval: (0.051247, 0.092808) 
## 
## Relative Risk:
##    Parameter Estimate:  1.852 
##   Est Std Err log(RR):  0.092521 
##               p-value:  2.7185e-11 
##     95% Conf Interval: (1.5449, 2.2203) 
## 
## Odds Ratio:
##    Parameter Estimate:  2.0102 
##   Est Std Err log(OR):  0.10412 
##               p-value:  1.9986e-11 
##     95% Conf Interval: (1.6391, 2.4653)</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-1" tabindex="-1"></a><span class="do">## With a continuous outcome, CDE(M=1) = E(Y_{A=1,M=1}) - E(Y_{A=0,M=1})</span></span>
<span id="cb100-2"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-2" tabindex="-1"></a>ltmle_gcomp_CDE_M0 <span class="ot">&lt;-</span> <span class="fu">ltmle</span>(<span class="at">data =</span> df_score,</span>
<span id="cb100-3"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-3" tabindex="-1"></a>                            <span class="at">Anodes =</span> <span class="fu">c</span>(<span class="st">&quot;edu&quot;</span>, <span class="st">&quot;smoking&quot;</span>),</span>
<span id="cb100-4"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-4" tabindex="-1"></a>                            <span class="at">Lnodes =</span> <span class="fu">c</span>(<span class="st">&quot;phys&quot;</span>, <span class="st">&quot;occupation&quot;</span>),</span>
<span id="cb100-5"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-5" tabindex="-1"></a>                            <span class="at">Ynodes =</span> <span class="fu">c</span>(<span class="st">&quot;score&quot;</span>), <span class="co"># continous outcome</span></span>
<span id="cb100-6"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-6" tabindex="-1"></a>                            <span class="at">survivalOutcome =</span> <span class="cn">FALSE</span>,</span>
<span id="cb100-7"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-7" tabindex="-1"></a>                            <span class="at">Qform =</span> Q_formulas_score, <span class="co"># Q formulas</span></span>
<span id="cb100-8"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-8" tabindex="-1"></a>                            <span class="at">gform =</span> g_formulas, <span class="co"># g formulas</span></span>
<span id="cb100-9"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-9" tabindex="-1"></a>                            <span class="at">abar =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>),</span>
<span id="cb100-10"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-10" tabindex="-1"></a>                                        <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)), <span class="co"># Y_{A=1,M=0} vs Y_{A=0,M=0}</span></span>
<span id="cb100-11"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-11" tabindex="-1"></a>                            <span class="at">rule =</span> <span class="cn">NULL</span>,</span>
<span id="cb100-12"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-12" tabindex="-1"></a>                            <span class="at">gbounds =</span> <span class="fu">c</span>(<span class="fl">0.01</span>, <span class="dv">1</span>), <span class="co"># by default</span></span>
<span id="cb100-13"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-13" tabindex="-1"></a>                            <span class="at">Yrange =</span> <span class="cn">NULL</span>,</span>
<span id="cb100-14"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-14" tabindex="-1"></a>                            <span class="at">deterministic.g.function =</span> <span class="cn">NULL</span>,</span>
<span id="cb100-15"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-15" tabindex="-1"></a>                            <span class="at">stratify =</span> <span class="cn">FALSE</span>,</span>
<span id="cb100-16"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-16" tabindex="-1"></a>                            <span class="at">SL.library =</span> <span class="st">&quot;glm&quot;</span>,</span>
<span id="cb100-17"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-17" tabindex="-1"></a>                            <span class="at">SL.cvControl =</span> <span class="fu">list</span>(),</span>
<span id="cb100-18"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-18" tabindex="-1"></a>                            <span class="at">estimate.time =</span> <span class="cn">FALSE</span>,</span>
<span id="cb100-19"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-19" tabindex="-1"></a>                            <span class="at">gcomp =</span> <span class="cn">TRUE</span>, <span class="co"># should be TRUE for g-computation</span></span>
<span id="cb100-20"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-20" tabindex="-1"></a>                            <span class="at">iptw.only =</span> <span class="cn">FALSE</span>,</span>
<span id="cb100-21"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-21" tabindex="-1"></a>                            <span class="at">deterministic.Q.function =</span> <span class="cn">NULL</span>,</span>
<span id="cb100-22"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-22" tabindex="-1"></a>                            <span class="at">variance.method =</span> <span class="st">&quot;ic&quot;</span>,</span>
<span id="cb100-23"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-23" tabindex="-1"></a>                            <span class="at">observation.weights =</span> <span class="cn">NULL</span>,</span>
<span id="cb100-24"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-24" tabindex="-1"></a>                            <span class="at">id =</span> <span class="cn">NULL</span>)</span>
<span id="cb100-25"><a href="estimate-the-cde-using-the-ltmle-package.html#cb100-25" tabindex="-1"></a><span class="fu">summary</span>(ltmle_gcomp_CDE_M0)</span></code></pre></div>
<pre><code>## Estimator:  gcomp 
## Warning: inference for gcomp is not accurate! It is based on TMLE influence curves.
## Call:
## ltmle(data = df_score, Anodes = c(&quot;edu&quot;, &quot;smoking&quot;), Lnodes = c(&quot;phys&quot;, 
##     &quot;occupation&quot;), Ynodes = c(&quot;score&quot;), survivalOutcome = FALSE, 
##     Qform = Q_formulas_score, gform = g_formulas, abar = list(c(1, 
##         0), c(0, 0)), rule = NULL, gbounds = c(0.01, 1), Yrange = NULL, 
##     deterministic.g.function = NULL, stratify = FALSE, SL.library = &quot;glm&quot;, 
##     SL.cvControl = list(), estimate.time = FALSE, gcomp = TRUE, 
##     iptw.only = FALSE, deterministic.Q.function = NULL, variance.method = &quot;ic&quot;, 
##     observation.weights = NULL, id = NULL)
## 
## Treatment Estimate:
##    Parameter Estimate:  37.537 
##     Estimated Std Err:  0.35058 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (36.849, 38.224) 
## 
## Control Estimate:
##    Parameter Estimate:  49.669 
##     Estimated Std Err:  0.34282 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (48.997, 50.341) 
## 
## Additive Treatment Effect:
##    Parameter Estimate:  -12.132 
##     Estimated Std Err:  0.48796 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (-13.089, -11.176)</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb102-1" tabindex="-1"></a><span class="co"># in order to apply quasibinomial regressions, ltmle automatically transformed </span></span>
<span id="cb102-2"><a href="estimate-the-cde-using-the-ltmle-package.html#cb102-2" tabindex="-1"></a><span class="co"># the continuous outcome by Y_transformed = (Y - min(Y)) / range(Y)</span></span>
<span id="cb102-3"><a href="estimate-the-cde-using-the-ltmle-package.html#cb102-3" tabindex="-1"></a><span class="co"># so that the range of Y_transformed is [0,1], </span></span>
<span id="cb102-4"><a href="estimate-the-cde-using-the-ltmle-package.html#cb102-4" tabindex="-1"></a><span class="co"># Then, the results are back-transformed.</span></span>
<span id="cb102-5"><a href="estimate-the-cde-using-the-ltmle-package.html#cb102-5" tabindex="-1"></a>ltmle_gcomp_CDE_M0<span class="sc">$</span>transformOutcome</span></code></pre></div>
<pre><code>## [1] TRUE
## attr(,&quot;Yrange&quot;)
## [1] -49.40414  97.00414</code></pre>
<p>We can see that the results are exactly the same as the previous manual calculation by ICE for the binary outcome. It is slightly different for the continuous outcome (because we did not apply a quasibinomial model on the min-max transformation in the manual calculation).</p>
</div>
</div>
<div id="iptw-estimator-of-the-cde" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> IPTW estimator of the CDE<a href="estimate-the-cde-using-the-ltmle-package.html#iptw-estimator-of-the-cde" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can express the CDE using coefficients of an MSM, where the MSM’s coefficients are estimated by IPTW.</p>
<p>The controlled direct effect is defined as <span class="math inline">\(\text{CDE}_m= \mathbb{E}(Y_{am}) - \mathbb{E}(Y_{a^*m})\)</span>.</p>
<p>Using the following MSM
<span class="math display" id="eq:MSMCDE">\[\begin{equation}
  \mathbb{E}(Y_{am}) = \alpha_0 + \alpha_A a + \alpha_M m + \alpha_{A \ast M} a \times m
  \tag{5.1}
\end{equation}\]</span>
the controlled direct effect (keeping the mediator constant to the value <span class="math inline">\(M=m\)</span>) can be expressed using the coefficients of the MSM <a href="estimate-the-cde-using-the-ltmle-package.html#eq:MSMCDE">(5.1)</a>:
<span class="math display">\[\begin{align*}
  \text{CDE}_m &amp;= (\alpha_0 + \alpha_A a + \alpha_M m + \alpha_{A \ast M} a \times m) - (\alpha_0 + \alpha_A a^* + \alpha_M m + \alpha_{A \ast M} a^* \times m) \\
  \text{CDE}_m &amp;= \alpha_A(a - a^* ) + \alpha_{A \ast M} \times (a - a^*) \times m
\end{align*}\]</span>
For a binary exposure <span class="math inline">\(A\)</span>, we have <span class="math inline">\(\text{CDE}_m=\alpha_A + \alpha_{A \ast M} \times m\)</span>.</p>
<div id="estimation-of-the-msm-coefficients-by-iptw" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Estimation of the MSM coefficients by IPTW<a href="estimate-the-cde-using-the-ltmle-package.html#estimation-of-the-msm-coefficients-by-iptw" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>MSM coefficients can be easily estimated using an Inverse Probability of Treatment (IPTW) approach based on weighted regressions.</p>
<p>In order to fit the MSM <a href="estimate-the-cde-using-the-ltmle-package.html#eq:MSMCDE">(5.1)</a>, we can use a linear regression of the (observed) outcome <span class="math inline">\(Y\)</span> on the exposure and mediator, weighted by individual stabilized weights <span class="math inline">\(sw_i\)</span> <span class="citation">(<a href="#ref-vanderweele2009">VanderWeele 2009</a>)</span>:
<span class="math display">\[\begin{equation}
  \mathbb{E}\left(Y \mid A,M\right) = \alpha_0 + \alpha_A a + \alpha_M m + \alpha_{A \ast M} a \times m
\end{equation}\]</span></p>
<p>where <span class="math inline">\(sw_i\)</span> is the product of two weights <span class="math inline">\(sw_i = sw_{A,i} \times sw_{M,i}\)</span>,</p>
<p><span class="math inline">\(sw_{A,i}=\frac{P(A=a_i)}{P(A=a_i \mid L(0)=l(0)_i)}\)</span> and <span class="math inline">\(sw_{M,i}=\frac{P(M=m_i \mid A=a_i)}{P(M = m_i \mid A=a_i,L(0)=l(0)_i, L(1)=l(1)_i)}\)</span>.</p>
<p>The “no-unmeasured confounding” assumption is addressed by the application of weights <span class="math inline">\(sw_i\)</span>, which balances confounders <span class="math inline">\(L(0)\)</span> relative to the exposure-outcome <span class="math inline">\(A-Y\)</span> relationship, and balance the set of confounders <span class="math inline">\(\{L(0),A,L(1)\}\)</span> relative to the mediator-outcome <span class="math inline">\(M-Y\)</span> relationship.</p>
<p>Below, we estimate the CDE by hand:</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-1" tabindex="-1"></a><span class="do">### MSM of CDE, estimated by IPTW</span></span>
<span id="cb104-2"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-2" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb104-3"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-3" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">&quot;data/df.csv&quot;</span>)</span>
<span id="cb104-4"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-4" tabindex="-1"></a></span>
<span id="cb104-5"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-5" tabindex="-1"></a><span class="do">## 1. Stabilized weight for the exposure sw_{A,i}</span></span>
<span id="cb104-6"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-6" tabindex="-1"></a><span class="co"># 1a. Estimate g(A=a_i|L(0)) (denominator of the weight)</span></span>
<span id="cb104-7"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-7" tabindex="-1"></a>g_A_L <span class="ot">&lt;-</span> <span class="fu">glm</span>(edu <span class="sc">~</span> sex <span class="sc">+</span> low_par_edu,</span>
<span id="cb104-8"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-8" tabindex="-1"></a>             <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="at">data =</span> df)</span>
<span id="cb104-9"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-9" tabindex="-1"></a><span class="co"># 1b. Predict each individual&#39;s probability of being exposed to her own exposure</span></span>
<span id="cb104-10"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-10" tabindex="-1"></a><span class="co"># the predicted probability of the observed treatment g(A = a_i | L(0)) is :</span></span>
<span id="cb104-11"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-11" tabindex="-1"></a>gAi_L <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="fu">nrow</span>(df))</span>
<span id="cb104-12"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-12" tabindex="-1"></a>gAi_L[df<span class="sc">$</span>edu <span class="sc">==</span> <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">predict</span>(g_A_L, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)[df<span class="sc">$</span>edu <span class="sc">==</span> <span class="dv">1</span>]</span>
<span id="cb104-13"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-13" tabindex="-1"></a>gAi_L[df<span class="sc">$</span>edu <span class="sc">==</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">predict</span>(g_A_L, <span class="at">type=</span><span class="st">&quot;response&quot;</span>))[df<span class="sc">$</span>edu <span class="sc">==</span> <span class="dv">0</span>]</span>
<span id="cb104-14"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-14" tabindex="-1"></a></span>
<span id="cb104-15"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-15" tabindex="-1"></a><span class="co"># 1c. Estimate g(A=a_i) (numerator of the weight)</span></span>
<span id="cb104-16"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-16" tabindex="-1"></a>g_A <span class="ot">&lt;-</span> <span class="fu">glm</span>(edu <span class="sc">~</span> <span class="dv">1</span>, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="at">data =</span> df)</span>
<span id="cb104-17"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-17" tabindex="-1"></a><span class="co"># 1d. Predict each individual&#39;s probability of being exposed to her own exposure</span></span>
<span id="cb104-18"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-18" tabindex="-1"></a><span class="co"># the predicted probability of the observed treatment g(A = a_i) is :</span></span>
<span id="cb104-19"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-19" tabindex="-1"></a>gAi <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="fu">nrow</span>(df))</span>
<span id="cb104-20"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-20" tabindex="-1"></a>gAi[df<span class="sc">$</span>edu <span class="sc">==</span> <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">predict</span>(g_A, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)[df<span class="sc">$</span>edu <span class="sc">==</span> <span class="dv">1</span>]</span>
<span id="cb104-21"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-21" tabindex="-1"></a>gAi[df<span class="sc">$</span>edu <span class="sc">==</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">predict</span>(g_A, <span class="at">type=</span><span class="st">&quot;response&quot;</span>))[df<span class="sc">$</span>edu <span class="sc">==</span> <span class="dv">0</span>]</span>
<span id="cb104-22"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-22" tabindex="-1"></a></span>
<span id="cb104-23"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-23" tabindex="-1"></a><span class="co"># 1e. Calculate the stabilized weight for the exposure A: sw_{A,i}</span></span>
<span id="cb104-24"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-24" tabindex="-1"></a>sw_Ai <span class="ot">&lt;-</span> gAi <span class="sc">/</span> gAi_L</span>
<span id="cb104-25"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-25" tabindex="-1"></a></span>
<span id="cb104-26"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-26" tabindex="-1"></a><span class="do">## 2. Stabilized weight for the mediator sw_{M,i}</span></span>
<span id="cb104-27"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-27" tabindex="-1"></a><span class="co"># 2a. Estimate g(M=m_i|L(0),A,L(1)) (denominator of the weight)</span></span>
<span id="cb104-28"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-28" tabindex="-1"></a>g_M_L <span class="ot">&lt;-</span> <span class="fu">glm</span>(smoking <span class="sc">~</span> sex <span class="sc">+</span> low_par_edu <span class="sc">+</span> edu <span class="sc">+</span> phys <span class="sc">+</span> occupation,</span>
<span id="cb104-29"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-29" tabindex="-1"></a>             <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="at">data =</span> df)</span>
<span id="cb104-30"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-30" tabindex="-1"></a><span class="co"># 2b. Predict each individual&#39;s probability of being exposed to her own exposure</span></span>
<span id="cb104-31"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-31" tabindex="-1"></a><span class="co"># the predicted probability of the observed treatment g(A = a_i | L(0)) is :</span></span>
<span id="cb104-32"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-32" tabindex="-1"></a>gMi_L <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="fu">nrow</span>(df))</span>
<span id="cb104-33"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-33" tabindex="-1"></a>gMi_L[df<span class="sc">$</span>smoking <span class="sc">==</span> <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">predict</span>(g_M_L, </span>
<span id="cb104-34"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-34" tabindex="-1"></a>                                  <span class="at">type=</span><span class="st">&quot;response&quot;</span>)[df<span class="sc">$</span>smoking <span class="sc">==</span> <span class="dv">1</span>]</span>
<span id="cb104-35"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-35" tabindex="-1"></a>gMi_L[df<span class="sc">$</span>smoking <span class="sc">==</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">predict</span>(g_M_L, </span>
<span id="cb104-36"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-36" tabindex="-1"></a>                                       <span class="at">type=</span><span class="st">&quot;response&quot;</span>))[df<span class="sc">$</span>smoking <span class="sc">==</span> <span class="dv">0</span>]</span>
<span id="cb104-37"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-37" tabindex="-1"></a></span>
<span id="cb104-38"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-38" tabindex="-1"></a><span class="co"># 2c. Estimate g(M=m_i|A) (numerator of the weight)</span></span>
<span id="cb104-39"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-39" tabindex="-1"></a>g_M_A <span class="ot">&lt;-</span> <span class="fu">glm</span>(smoking <span class="sc">~</span> edu, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="at">data =</span> df)</span>
<span id="cb104-40"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-40" tabindex="-1"></a><span class="co"># 2d. Predict each individual&#39;s probability of being exposed to her own exposure</span></span>
<span id="cb104-41"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-41" tabindex="-1"></a><span class="co"># the predicted probability of the observed treatment g(M = m_i|A) is :</span></span>
<span id="cb104-42"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-42" tabindex="-1"></a>gMi_A <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="fu">nrow</span>(df))</span>
<span id="cb104-43"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-43" tabindex="-1"></a>gMi_A[df<span class="sc">$</span>smoking<span class="sc">==</span><span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">predict</span>(g_M_A, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)[df<span class="sc">$</span>smoking<span class="sc">==</span><span class="dv">1</span>]</span>
<span id="cb104-44"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-44" tabindex="-1"></a>gMi_A[df<span class="sc">$</span>smoking<span class="sc">==</span><span class="dv">0</span>] <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">predict</span>(g_M_A, <span class="at">type=</span><span class="st">&quot;response&quot;</span>))[df<span class="sc">$</span>smoking<span class="sc">==</span><span class="dv">0</span>]</span>
<span id="cb104-45"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-45" tabindex="-1"></a><span class="co"># 2e. Calculate the stabilized weight for the mediator M: sw_{M,i}</span></span>
<span id="cb104-46"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-46" tabindex="-1"></a>sw_Mi <span class="ot">&lt;-</span> gMi_A <span class="sc">/</span> gMi_L</span>
<span id="cb104-47"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-47" tabindex="-1"></a></span>
<span id="cb104-48"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-48" tabindex="-1"></a><span class="do">## 3. Define the individual stabilized weight for the CDE_m</span></span>
<span id="cb104-49"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-49" tabindex="-1"></a>sw_cde <span class="ot">&lt;-</span> sw_Ai <span class="sc">*</span> sw_Mi</span>
<span id="cb104-50"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-50" tabindex="-1"></a></span>
<span id="cb104-51"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-51" tabindex="-1"></a><span class="do">## 4. Estimate coefficients of the MSM using a weighted regression E(Y | A, sex)</span></span>
<span id="cb104-52"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-52" tabindex="-1"></a><span class="co"># a GLM with gaussian family can be applied to estimate risk differences</span></span>
<span id="cb104-53"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-53" tabindex="-1"></a>msm_cde <span class="ot">&lt;-</span> <span class="fu">glm</span>(death <span class="sc">~</span> edu <span class="sc">+</span> smoking <span class="sc">+</span> edu<span class="sc">:</span>smoking,</span>
<span id="cb104-54"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-54" tabindex="-1"></a>               <span class="at">weights =</span> sw_cde,</span>
<span id="cb104-55"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-55" tabindex="-1"></a>               <span class="at">family =</span> <span class="st">&quot;gaussian&quot;</span>,</span>
<span id="cb104-56"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-56" tabindex="-1"></a>               <span class="at">data =</span> df)</span>
<span id="cb104-57"><a href="estimate-the-cde-using-the-ltmle-package.html#cb104-57" tabindex="-1"></a><span class="fu">coef</span>(msm_cde)</span></code></pre></div>
<pre><code>## (Intercept)         edu     smoking edu:smoking 
##  0.08293313  0.07044677  0.11974047  0.14206356</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb106-1" tabindex="-1"></a><span class="do">## 5. Estimate CDE for m=0 and for m=1 using the MSM&#39;s coefficients</span></span>
<span id="cb106-2"><a href="estimate-the-cde-using-the-ltmle-package.html#cb106-2" tabindex="-1"></a>CDE_mis0 <span class="ot">&lt;-</span> <span class="fu">coef</span>(msm_cde)[<span class="st">&quot;edu&quot;</span>] <span class="sc">+</span> <span class="dv">0</span> <span class="sc">*</span> <span class="fu">coef</span>(msm_cde)[<span class="st">&quot;edu:smoking&quot;</span>]</span>
<span id="cb106-3"><a href="estimate-the-cde-using-the-ltmle-package.html#cb106-3" tabindex="-1"></a>CDE_mis0</span></code></pre></div>
<pre><code>##        edu 
## 0.07044677</code></pre>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb108-1" tabindex="-1"></a><span class="do">## Note: we will see below that the ltmle package use a logistic model for the MSM</span></span>
<span id="cb108-2"><a href="estimate-the-cde-using-the-ltmle-package.html#cb108-2" tabindex="-1"></a>msm_cde_logit <span class="ot">&lt;-</span> <span class="fu">glm</span>(death <span class="sc">~</span> edu <span class="sc">+</span> smoking <span class="sc">+</span> edu<span class="sc">:</span>smoking,</span>
<span id="cb108-3"><a href="estimate-the-cde-using-the-ltmle-package.html#cb108-3" tabindex="-1"></a>                     <span class="at">weights =</span> sw_cde,</span>
<span id="cb108-4"><a href="estimate-the-cde-using-the-ltmle-package.html#cb108-4" tabindex="-1"></a>                     <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>,</span>
<span id="cb108-5"><a href="estimate-the-cde-using-the-ltmle-package.html#cb108-5" tabindex="-1"></a>                     <span class="at">data =</span> df)</span>
<span id="cb108-6"><a href="estimate-the-cde-using-the-ltmle-package.html#cb108-6" tabindex="-1"></a><span class="fu">coef</span>(msm_cde_logit)</span></code></pre></div>
<pre><code>## (Intercept)         edu     smoking edu:smoking 
##  -2.4031458   0.6948115   1.0334784   0.3322800</code></pre>
</div>
<div id="iptw-estmation-using-the-ltmle-package" class="section level3 hasAnchor" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> IPTW estmation using the ltmle package<a href="estimate-the-cde-using-the-ltmle-package.html#iptw-estmation-using-the-ltmle-package" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <code>ltmle</code> package can be used to estimate Controlled Direct Effects by IPTW, as shown below.</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-1" tabindex="-1"></a><span class="fu">library</span>(ltmle)</span>
<span id="cb110-2"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-2" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb110-3"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-3" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">&quot;data/df.csv&quot;</span>)</span>
<span id="cb110-4"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-4" tabindex="-1"></a></span>
<span id="cb110-5"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-5" tabindex="-1"></a>df_death <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(X, subjid, score))</span>
<span id="cb110-6"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-6" tabindex="-1"></a>df_score <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(X, subjid, death))</span>
<span id="cb110-7"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-7" tabindex="-1"></a></span>
<span id="cb110-8"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-8" tabindex="-1"></a><span class="do">## 1) Define Q formulas (Qbar_L1 and Qbar_Y functions)</span></span>
<span id="cb110-9"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-9" tabindex="-1"></a><span class="do">## (not needed if you only want to apply an IPTW estimation)</span></span>
<span id="cb110-10"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-10" tabindex="-1"></a>Q_formulas_death <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">phys =</span> <span class="st">&quot;Q.kplus1 ~ sex + low_par_edu + edu&quot;</span>,</span>
<span id="cb110-11"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-11" tabindex="-1"></a>                      <span class="at">death =</span> <span class="st">&quot;Q.kplus1 ~ sex + low_par_edu + phys + occupation +</span></span>
<span id="cb110-12"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-12" tabindex="-1"></a><span class="st">                               edu * smoking&quot;</span>) <span class="co"># add interaction</span></span>
<span id="cb110-13"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-13" tabindex="-1"></a></span>
<span id="cb110-14"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-14" tabindex="-1"></a><span class="do">## 2) Define g formulas (needed for the ltmle package) but they are not used</span></span>
<span id="cb110-15"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-15" tabindex="-1"></a><span class="co">#    with the g-computation estimator</span></span>
<span id="cb110-16"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-16" tabindex="-1"></a>g_formulas <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;edu ~ sex + low_par_edu&quot;</span>, </span>
<span id="cb110-17"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-17" tabindex="-1"></a>                <span class="st">&quot;smoking ~ sex + low_par_edu + edu + phys + occupation&quot;</span>)</span>
<span id="cb110-18"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-18" tabindex="-1"></a></span>
<span id="cb110-19"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-19" tabindex="-1"></a><span class="do">## 3) Use the ltmle() function</span></span>
<span id="cb110-20"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-20" tabindex="-1"></a><span class="do">## With a binary outcome, CDE(M=1) = P(Y_{A=1,M=0} = 1) - P(Y_{A=0,M=0} = 1)</span></span>
<span id="cb110-21"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-21" tabindex="-1"></a>ltmle_iptw_CDE_M0 <span class="ot">&lt;-</span> <span class="fu">ltmle</span>(<span class="at">data =</span> df_death,</span>
<span id="cb110-22"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-22" tabindex="-1"></a>                           <span class="at">Anodes =</span> <span class="fu">c</span>(<span class="st">&quot;edu&quot;</span>, <span class="st">&quot;smoking&quot;</span>),</span>
<span id="cb110-23"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-23" tabindex="-1"></a>                           <span class="at">Lnodes =</span> <span class="fu">c</span>(<span class="st">&quot;phys&quot;</span>, <span class="st">&quot;occupation&quot;</span>),</span>
<span id="cb110-24"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-24" tabindex="-1"></a>                           <span class="at">Ynodes =</span> <span class="fu">c</span>(<span class="st">&quot;death&quot;</span>), <span class="co"># binary outcome</span></span>
<span id="cb110-25"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-25" tabindex="-1"></a>                           <span class="at">survivalOutcome =</span> <span class="cn">FALSE</span>,</span>
<span id="cb110-26"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-26" tabindex="-1"></a>                           <span class="at">Qform =</span> Q_formulas_death, <span class="co"># Q formulas</span></span>
<span id="cb110-27"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-27" tabindex="-1"></a>                           <span class="at">gform =</span> g_formulas, <span class="co"># g formulas</span></span>
<span id="cb110-28"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-28" tabindex="-1"></a>                           <span class="at">abar =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>),</span>
<span id="cb110-29"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-29" tabindex="-1"></a>                                       <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)), <span class="co"># EY_{A=1,M=0} vs EY_{A=0,M=0}</span></span>
<span id="cb110-30"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-30" tabindex="-1"></a>                           <span class="at">rule =</span> <span class="cn">NULL</span>,</span>
<span id="cb110-31"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-31" tabindex="-1"></a>                           <span class="at">gbounds =</span> <span class="fu">c</span>(<span class="fl">0.01</span>, <span class="dv">1</span>), <span class="co"># truncation of g, by default</span></span>
<span id="cb110-32"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-32" tabindex="-1"></a>                           <span class="at">Yrange =</span> <span class="cn">NULL</span>,</span>
<span id="cb110-33"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-33" tabindex="-1"></a>                           <span class="at">deterministic.g.function =</span> <span class="cn">NULL</span>,</span>
<span id="cb110-34"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-34" tabindex="-1"></a>                           <span class="at">stratify =</span> <span class="cn">FALSE</span>,</span>
<span id="cb110-35"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-35" tabindex="-1"></a>                           <span class="at">SL.library =</span> <span class="st">&quot;glm&quot;</span>, <span class="co"># better to used the SuperLearner</span></span>
<span id="cb110-36"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-36" tabindex="-1"></a>                           <span class="at">SL.cvControl =</span> <span class="fu">list</span>(),</span>
<span id="cb110-37"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-37" tabindex="-1"></a>                           <span class="at">estimate.time =</span> <span class="cn">FALSE</span>,</span>
<span id="cb110-38"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-38" tabindex="-1"></a>                           <span class="at">gcomp =</span> <span class="cn">FALSE</span>, </span>
<span id="cb110-39"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-39" tabindex="-1"></a>                           <span class="at">iptw.only =</span> <span class="cn">TRUE</span>, <span class="co"># to use only the IPTW estimator</span></span>
<span id="cb110-40"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-40" tabindex="-1"></a>                           <span class="at">deterministic.Q.function =</span> <span class="cn">NULL</span>,</span>
<span id="cb110-41"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-41" tabindex="-1"></a>                           <span class="at">variance.method =</span> <span class="st">&quot;ic&quot;</span>,</span>
<span id="cb110-42"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-42" tabindex="-1"></a>                           <span class="at">observation.weights =</span> <span class="cn">NULL</span>,</span>
<span id="cb110-43"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-43" tabindex="-1"></a>                           <span class="at">id =</span> <span class="cn">NULL</span>)</span>
<span id="cb110-44"><a href="estimate-the-cde-using-the-ltmle-package.html#cb110-44" tabindex="-1"></a><span class="fu">summary</span>(ltmle_iptw_CDE_M0, <span class="at">estimator =</span> <span class="st">&quot;iptw&quot;</span>)</span></code></pre></div>
<pre><code>## Estimator:  iptw 
## Call:
## ltmle(data = df_death, Anodes = c(&quot;edu&quot;, &quot;smoking&quot;), Lnodes = c(&quot;phys&quot;, 
##     &quot;occupation&quot;), Ynodes = c(&quot;death&quot;), survivalOutcome = FALSE, 
##     Qform = Q_formulas_death, gform = g_formulas, abar = list(c(1, 
##         0), c(0, 0)), rule = NULL, gbounds = c(0.01, 1), Yrange = NULL, 
##     deterministic.g.function = NULL, stratify = FALSE, SL.library = &quot;glm&quot;, 
##     SL.cvControl = list(), estimate.time = FALSE, gcomp = FALSE, 
##     iptw.only = TRUE, deterministic.Q.function = NULL, variance.method = &quot;ic&quot;, 
##     observation.weights = NULL, id = NULL)
## 
## Treatment Estimate:
##    Parameter Estimate:  0.15338 
##     Estimated Std Err:  0.008554 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (0.13661, 0.17015) 
## 
## Control Estimate:
##    Parameter Estimate:  0.082933 
##     Estimated Std Err:  0.0063406 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (0.070506, 0.09536) 
## 
## Additive Treatment Effect:
##    Parameter Estimate:  0.070447 
##     Estimated Std Err:  0.010648 
##               p-value:  3.6865e-11 
##     95% Conf Interval: (0.049578, 0.091316) 
## 
## Relative Risk:
##    Parameter Estimate:  1.8494 
##   Est Std Err log(RR):  0.094633 
##               p-value:  8.1651e-11 
##     95% Conf Interval: (1.5363, 2.2263) 
## 
## Odds Ratio:
##    Parameter Estimate:  2.0033 
##   Est Std Err log(OR):  0.10625 
##               p-value:  6.1821e-11 
##     95% Conf Interval: (1.6267, 2.4671)</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb112-1" tabindex="-1"></a>ltmle_iptw_CDE_M0<span class="sc">$</span>beta.iptw</span></code></pre></div>
<pre><code>## (Intercept)           A 
##  -2.4031458   0.6948115</code></pre>
</div>
</div>
<div id="tmle-estimator-of-the-cde" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> TMLE estimator of the CDE<a href="estimate-the-cde-using-the-ltmle-package.html#tmle-estimator-of-the-cde" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Of course, the main interest of the <code>ltmle</code> package is to apply a TMLE estimator.</p>
<p>As with the G-computation method by iterative conditional expectation, the TMLE procedure relies on the estimation of 2 <span class="math inline">\(\bar{Q}\)</span> functions:</p>
<ul>
<li><span class="math inline">\(\bar{Q}_{L(2)}(A=a,M=m) = \mathbb{E}(Y \mid L(0),A,L(1),M)\)</span></li>
<li>and <span class="math inline">\(\bar{Q}_{L(1)} = \mathbb{E}(\hat{\bar{Q}}_{L(2)}(A=a,M=m) \mid L(0),A)\)</span>;</li>
</ul>
<p>And as with the IPTW method, the TMLE procedure relies also on the estimation of the 2 treatment mechanisms <span class="math inline">\(g\)</span>:</p>
<ul>
<li><span class="math inline">\(g_A(L(0)) = P(A=1 \mid L(0))\)</span></li>
<li>and <span class="math inline">\(g_M(L(0),A,L(1)) = P(M=1 \mid L(0),A,L(1))\)</span>.</li>
</ul>
<div id="for-binary-outcomes" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> For binary outcomes<a href="estimate-the-cde-using-the-ltmle-package.html#for-binary-outcomes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-1" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb114-2"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">&quot;data/df.csv&quot;</span>)</span>
<span id="cb114-3"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-3" tabindex="-1"></a></span>
<span id="cb114-4"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-4" tabindex="-1"></a><span class="fu">library</span>(ltmle)</span>
<span id="cb114-5"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-5" tabindex="-1"></a><span class="fu">library</span>(SuperLearner)</span>
<span id="cb114-6"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-6" tabindex="-1"></a><span class="fu">library</span>(hal9001)</span>
<span id="cb114-7"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-7" tabindex="-1"></a><span class="do">## 1) Define the formulas for the estimation of the 2 barQ functions and 2 g functions</span></span>
<span id="cb114-8"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-8" tabindex="-1"></a><span class="co"># Note that it is possible to specify the A*M interaction, if we really want to</span></span>
<span id="cb114-9"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-9" tabindex="-1"></a><span class="co"># take it into account.</span></span>
<span id="cb114-10"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-10" tabindex="-1"></a><span class="do">## Define Q formulas (Qbar_L1 and Qbar_Y functions)</span></span>
<span id="cb114-11"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-11" tabindex="-1"></a>Qform <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">phys =</span> <span class="st">&quot;Q.kplus1 ~ sex + low_par_edu + edu&quot;</span>,</span>
<span id="cb114-12"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-12" tabindex="-1"></a>           <span class="at">death =</span> <span class="st">&quot;Q.kplus1 ~ sex + low_par_edu + phys + occupation +</span></span>
<span id="cb114-13"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-13" tabindex="-1"></a><span class="st">                    edu * smoking&quot;</span>)</span>
<span id="cb114-14"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-14" tabindex="-1"></a></span>
<span id="cb114-15"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-15" tabindex="-1"></a><span class="do">## Define the formulas for the estimation of the 2 g function</span></span>
<span id="cb114-16"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-16" tabindex="-1"></a>gform <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;edu ~ sex + low_par_edu&quot;</span>,</span>
<span id="cb114-17"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-17" tabindex="-1"></a>           <span class="st">&quot;smoking ~ sex + low_par_edu + edu + phys + occupation&quot;</span>)</span>
<span id="cb114-18"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-18" tabindex="-1"></a></span>
<span id="cb114-19"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-19" tabindex="-1"></a><span class="do">## The data frame should follow the time-ordering of the nodes</span></span>
<span id="cb114-20"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-20" tabindex="-1"></a>data_binary <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, <span class="at">select =</span> <span class="fu">c</span>(sex, low_par_edu,</span>
<span id="cb114-21"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-21" tabindex="-1"></a>                                     edu, phys, occupation,</span>
<span id="cb114-22"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-22" tabindex="-1"></a>                                     smoking, death))</span>
<span id="cb114-23"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-23" tabindex="-1"></a></span>
<span id="cb114-24"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-24" tabindex="-1"></a><span class="do">## Choose a family of data-adaptive algorithms from the SuperLearner package</span></span>
<span id="cb114-25"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-25" tabindex="-1"></a><span class="co"># Define the SL.interaction.back learner from the SL.step.interaction</span></span>
<span id="cb114-26"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-26" tabindex="-1"></a>SL.interaction.back <span class="ot">=</span> <span class="cf">function</span>(...) {</span>
<span id="cb114-27"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-27" tabindex="-1"></a>  <span class="fu">SL.step.interaction</span>(..., <span class="at">direction =</span> <span class="st">&quot;backward&quot;</span>)</span>
<span id="cb114-28"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-28" tabindex="-1"></a>}</span>
<span id="cb114-29"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-29" tabindex="-1"></a></span>
<span id="cb114-30"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-30" tabindex="-1"></a><span class="co"># Define an ad-hoc hal learner that can be applied with continous outcomes</span></span>
<span id="cb114-31"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-31" tabindex="-1"></a>SL.hal9001.Qbar <span class="ot">&lt;-</span> <span class="cf">function</span> (Y, X, newX, family, obsWeights, id, <span class="at">max_degree =</span> <span class="dv">2</span>, </span>
<span id="cb114-32"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-32" tabindex="-1"></a>                             <span class="at">smoothness_orders =</span> <span class="dv">1</span>, <span class="at">num_knots =</span> <span class="dv">5</span>, ...) {</span>
<span id="cb114-33"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-33" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.matrix</span>(X)) </span>
<span id="cb114-34"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-34" tabindex="-1"></a>    X <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(X)</span>
<span id="cb114-35"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-35" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(newX) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.matrix</span>(newX)) </span>
<span id="cb114-36"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-36" tabindex="-1"></a>    newX <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(newX)</span>
<span id="cb114-37"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-37" tabindex="-1"></a>  </span>
<span id="cb114-38"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-38" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(<span class="fu">unique</span>(Y)) <span class="sc">==</span> <span class="dv">2</span>) { <span class="co"># for binomial family</span></span>
<span id="cb114-39"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-39" tabindex="-1"></a>    hal_fit <span class="ot">&lt;-</span> hal9001<span class="sc">::</span><span class="fu">fit_hal</span>(<span class="at">Y =</span> Y, <span class="at">X =</span> X, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, </span>
<span id="cb114-40"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-40" tabindex="-1"></a>                                <span class="at">weights =</span> obsWeights, <span class="at">id =</span> id, <span class="at">max_degree =</span> max_degree, </span>
<span id="cb114-41"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-41" tabindex="-1"></a>                                <span class="at">smoothness_orders =</span> smoothness_orders, <span class="at">num_knots =</span> num_knots, </span>
<span id="cb114-42"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-42" tabindex="-1"></a>                                ...)</span>
<span id="cb114-43"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-43" tabindex="-1"></a>  }</span>
<span id="cb114-44"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-44" tabindex="-1"></a>  </span>
<span id="cb114-45"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-45" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(<span class="fu">unique</span>(Y)) <span class="sc">&gt;</span> <span class="dv">2</span>) { <span class="co"># for quasibinomial family</span></span>
<span id="cb114-46"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-46" tabindex="-1"></a>    hal_fit <span class="ot">&lt;-</span> hal9001<span class="sc">::</span><span class="fu">fit_hal</span>(<span class="at">Y =</span> Y, <span class="at">X =</span> X, <span class="at">family =</span> <span class="st">&quot;gaussian&quot;</span>, </span>
<span id="cb114-47"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-47" tabindex="-1"></a>                                <span class="at">weights =</span> obsWeights, <span class="at">id =</span> id, <span class="at">max_degree =</span> max_degree, </span>
<span id="cb114-48"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-48" tabindex="-1"></a>                                <span class="at">smoothness_orders =</span> smoothness_orders, <span class="at">num_knots =</span> num_knots, </span>
<span id="cb114-49"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-49" tabindex="-1"></a>                                ...)</span>
<span id="cb114-50"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-50" tabindex="-1"></a>  }</span>
<span id="cb114-51"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-51" tabindex="-1"></a>  </span>
<span id="cb114-52"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-52" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(newX)) {</span>
<span id="cb114-53"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-53" tabindex="-1"></a>    pred <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">predict</span>(hal_fit, <span class="at">new_data =</span> newX)</span>
<span id="cb114-54"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-54" tabindex="-1"></a>  }</span>
<span id="cb114-55"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-55" tabindex="-1"></a>  <span class="cf">else</span> {</span>
<span id="cb114-56"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-56" tabindex="-1"></a>    pred <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">predict</span>(hal_fit, <span class="at">new_data =</span> X)</span>
<span id="cb114-57"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-57" tabindex="-1"></a>  }</span>
<span id="cb114-58"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-58" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">object =</span> hal_fit)</span>
<span id="cb114-59"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-59" tabindex="-1"></a>  <span class="fu">class</span>(fit) <span class="ot">&lt;-</span> <span class="st">&quot;SL.hal9001&quot;</span></span>
<span id="cb114-60"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-60" tabindex="-1"></a>  out <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">pred =</span> pred, <span class="at">fit =</span> fit)</span>
<span id="cb114-61"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-61" tabindex="-1"></a>  <span class="fu">return</span>(out)</span>
<span id="cb114-62"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-62" tabindex="-1"></a>}</span>
<span id="cb114-63"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-63" tabindex="-1"></a><span class="fu">environment</span>(SL.hal9001.Qbar) <span class="ot">&lt;-</span><span class="fu">asNamespace</span>(<span class="st">&quot;SuperLearner&quot;</span>)</span>
<span id="cb114-64"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-64" tabindex="-1"></a></span>
<span id="cb114-65"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-65" tabindex="-1"></a><span class="do">## Define the SuperLearner library</span></span>
<span id="cb114-66"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-66" tabindex="-1"></a>SL.library <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">Q=</span><span class="fu">c</span>(<span class="st">&quot;SL.mean&quot;</span>,<span class="st">&quot;SL.glm&quot;</span>,<span class="st">&quot;SL.interaction.back&quot;</span>,<span class="st">&quot;SL.hal9001.Qbar&quot;</span>),</span>
<span id="cb114-67"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-67" tabindex="-1"></a>                   <span class="at">g=</span><span class="fu">c</span>(<span class="st">&quot;SL.mean&quot;</span>,<span class="st">&quot;SL.glm&quot;</span>,<span class="st">&quot;SL.interaction.back&quot;</span>,<span class="st">&quot;SL.hal9001&quot;</span>))</span>
<span id="cb114-68"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-68" tabindex="-1"></a></span>
<span id="cb114-69"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-69" tabindex="-1"></a></span>
<span id="cb114-70"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-70" tabindex="-1"></a><span class="do">## CDE, setting M=0</span></span>
<span id="cb114-71"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-71" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># for reproducibility with the SuperLearner</span></span>
<span id="cb114-72"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-72" tabindex="-1"></a>CDE_ltmle_M0_death <span class="ot">&lt;-</span> <span class="fu">ltmle</span>(<span class="at">data =</span> data_binary,</span>
<span id="cb114-73"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-73" tabindex="-1"></a>                            <span class="at">Anodes =</span> <span class="fu">c</span>(<span class="st">&quot;edu&quot;</span>, <span class="st">&quot;smoking&quot;</span>),</span>
<span id="cb114-74"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-74" tabindex="-1"></a>                            <span class="at">Lnodes =</span> <span class="fu">c</span>(<span class="st">&quot;phys&quot;</span>, </span>
<span id="cb114-75"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-75" tabindex="-1"></a>                                       <span class="st">&quot;occupation&quot;</span>), <span class="co"># intermediate L(1) +/- L(0)</span></span>
<span id="cb114-76"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-76" tabindex="-1"></a>                            <span class="at">Ynodes =</span> <span class="fu">c</span>(<span class="st">&quot;death&quot;</span>),</span>
<span id="cb114-77"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-77" tabindex="-1"></a>                            <span class="at">survivalOutcome =</span> <span class="cn">FALSE</span>, <span class="co"># TRUE for time-to-event outcomes Y</span></span>
<span id="cb114-78"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-78" tabindex="-1"></a>                            <span class="at">Qform =</span> Qform,</span>
<span id="cb114-79"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-79" tabindex="-1"></a>                            <span class="at">gform =</span> gform,</span>
<span id="cb114-80"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-80" tabindex="-1"></a>                            <span class="at">abar =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>), <span class="co"># counterfactual intervention do(A=1,M=0)</span></span>
<span id="cb114-81"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-81" tabindex="-1"></a>                                        <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)), <span class="co"># counterfactual intervention do(A=0,M=0)</span></span>
<span id="cb114-82"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-82" tabindex="-1"></a>                            <span class="at">SL.library =</span> SL.library,</span>
<span id="cb114-83"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-83" tabindex="-1"></a>                            <span class="at">estimate.time =</span> <span class="cn">FALSE</span>, <span class="co"># estimate computation time?</span></span>
<span id="cb114-84"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-84" tabindex="-1"></a>                            <span class="at">gcomp =</span> <span class="cn">FALSE</span>,</span>
<span id="cb114-85"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-85" tabindex="-1"></a>                            <span class="at">variance.method =</span> <span class="st">&quot;ic&quot;</span>) <span class="co"># a more robust variance can</span></span>
<span id="cb114-86"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-86" tabindex="-1"></a>                                                    <span class="co"># be estimated with</span></span>
<span id="cb114-87"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-87" tabindex="-1"></a>                                                    <span class="co"># variance.method = &quot;tmle&quot;</span></span>
<span id="cb114-88"><a href="estimate-the-cde-using-the-ltmle-package.html#cb114-88" tabindex="-1"></a><span class="fu">summary</span>(CDE_ltmle_M0_death, <span class="at">estimator =</span> <span class="st">&quot;tmle&quot;</span>)</span></code></pre></div>
<pre><code>## Estimator:  tmle 
## Call:
## ltmle(data = data_binary, Anodes = c(&quot;edu&quot;, &quot;smoking&quot;), Lnodes = c(&quot;phys&quot;, 
##     &quot;occupation&quot;), Ynodes = c(&quot;death&quot;), survivalOutcome = FALSE, 
##     Qform = Qform, gform = gform, abar = list(c(1, 0), c(0, 0)), 
##     SL.library = SL.library, estimate.time = FALSE, gcomp = FALSE, 
##     variance.method = &quot;ic&quot;)
## 
## Treatment Estimate:
##    Parameter Estimate:  0.15356 
##     Estimated Std Err:  0.0084833 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (0.13693, 0.17018) 
## 
## Control Estimate:
##    Parameter Estimate:  0.083222 
##     Estimated Std Err:  0.0063304 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (0.070815, 0.09563) 
## 
## Additive Treatment Effect:
##    Parameter Estimate:  0.070333 
##     Estimated Std Err:  0.010579 
##               p-value:  2.9617e-11 
##     95% Conf Interval: (0.049599, 0.091068) 
## 
## Relative Risk:
##    Parameter Estimate:  1.8451 
##   Est Std Err log(RR):  0.093958 
##               p-value:  7.0611e-11 
##     95% Conf Interval: (1.5348, 2.2182) 
## 
## Odds Ratio:
##    Parameter Estimate:  1.9984 
##   Est Std Err log(OR):  0.1055 
##               p-value:  5.2938e-11 
##     95% Conf Interval: (1.6251, 2.4575)</code></pre>
<p>The controlled direct effect of education on the probability of death, had the mediator been set to 0 for every participant, estimated by TMLE, is 7.03%, 95%CI=[4.96%, 9.10%].</p>
<p>Note that an estimation by IPTW is also available (because it relies on the g-functions that have been estimated in the process)</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb116-1" tabindex="-1"></a><span class="fu">summary</span>(CDE_ltmle_M0_death, <span class="at">estimator =</span> <span class="st">&quot;iptw&quot;</span>)</span></code></pre></div>
<pre><code>## Estimator:  iptw 
## Call:
## ltmle(data = data_binary, Anodes = c(&quot;edu&quot;, &quot;smoking&quot;), Lnodes = c(&quot;phys&quot;, 
##     &quot;occupation&quot;), Ynodes = c(&quot;death&quot;), survivalOutcome = FALSE, 
##     Qform = Qform, gform = gform, abar = list(c(1, 0), c(0, 0)), 
##     SL.library = SL.library, estimate.time = FALSE, gcomp = FALSE, 
##     variance.method = &quot;ic&quot;)
## 
## Treatment Estimate:
##    Parameter Estimate:  0.15344 
##     Estimated Std Err:  0.0085304 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (0.13672, 0.17016) 
## 
## Control Estimate:
##    Parameter Estimate:  0.082857 
##     Estimated Std Err:  0.0063367 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (0.070437, 0.095277) 
## 
## Additive Treatment Effect:
##    Parameter Estimate:  0.070583 
##     Estimated Std Err:  0.010626 
##               p-value:  3.0906e-11 
##     95% Conf Interval: (0.049756, 0.091411) 
## 
## Relative Risk:
##    Parameter Estimate:  1.8519 
##   Est Std Err log(RR):  0.094549 
##               p-value:  7.1654e-11 
##     95% Conf Interval: (1.5386, 2.2289) 
## 
## Odds Ratio:
##    Parameter Estimate:  2.0063 
##   Est Std Err log(OR):  0.10614 
##               p-value:  5.3857e-11 
##     95% Conf Interval: (1.6294, 2.4702)</code></pre>
<p>You can check which learner has been used:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb118-1" tabindex="-1"></a><span class="do">## for the propensity scores g</span></span>
<span id="cb118-2"><a href="estimate-the-cde-using-the-ltmle-package.html#cb118-2" tabindex="-1"></a>CDE_ltmle_M0_death<span class="sc">$</span>fit<span class="sc">$</span>g</span></code></pre></div>
<pre><code>## [[1]]
## [[1]]$edu
##                              Risk       Coef
## SL.mean_All             0.2409789 0.01398045
## SL.glm_All              0.2359616 0.00000000
## SL.interaction.back_All 0.2359616 0.98601955
## SL.hal9001_All          0.2359785 0.00000000
## 
## [[1]]$smoking
##                              Risk      Coef
## SL.mean_All             0.2429252 0.0000000
## SL.glm_All              0.2220183 0.0000000
## SL.interaction.back_All 0.2220183 0.5880339
## SL.hal9001_All          0.2220520 0.4119661
## 
## 
## [[2]]
## [[2]]$edu
##                              Risk       Coef
## SL.mean_All             0.2409789 0.01398045
## SL.glm_All              0.2359616 0.00000000
## SL.interaction.back_All 0.2359616 0.98601955
## SL.hal9001_All          0.2359785 0.00000000
## 
## [[2]]$smoking
##                              Risk      Coef
## SL.mean_All             0.2429252 0.0000000
## SL.glm_All              0.2220183 0.0000000
## SL.interaction.back_All 0.2220183 0.5880339
## SL.hal9001_All          0.2220520 0.4119661</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb120-1" tabindex="-1"></a><span class="do">## for the models of the outcome (Qbar)</span></span>
<span id="cb120-2"><a href="estimate-the-cde-using-the-ltmle-package.html#cb120-2" tabindex="-1"></a>CDE_ltmle_M0_death<span class="sc">$</span>fit<span class="sc">$</span>Q</span></code></pre></div>
<pre><code>## [[1]]
## [[1]]$phys
##                                 Risk      Coef
## SL.mean_All             0.0013590082 0.0000000
## SL.glm_All              0.0001867586 0.2704883
## SL.interaction.back_All 0.0001952437 0.0000000
## SL.hal9001.Qbar_All     0.0001864661 0.7295117
## 
## [[1]]$death
##                              Risk        Coef
## SL.mean_All             0.1905313 0.003179812
## SL.glm_All              0.1667929 0.864927364
## SL.interaction.back_All 0.1668328 0.000000000
## SL.hal9001.Qbar_All     0.1668952 0.131892823
## 
## 
## [[2]]
## [[2]]$phys
##                                 Risk      Coef
## SL.mean_All             4.935728e-04 0.0000000
## SL.glm_All              6.864426e-05 0.2665221
## SL.interaction.back_All 7.175876e-05 0.0000000
## SL.hal9001.Qbar_All     6.853114e-05 0.7334779
## 
## [[2]]$death
##                              Risk        Coef
## SL.mean_All             0.1905313 0.003179812
## SL.glm_All              0.1667929 0.864927364
## SL.interaction.back_All 0.1668328 0.000000000
## SL.hal9001.Qbar_All     0.1668952 0.131892823</code></pre>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb122-1" tabindex="-1"></a><span class="do">## In practice, the ltmle function estimates an MSM with 2 parameters </span></span>
<span id="cb122-2"><a href="estimate-the-cde-using-the-ltmle-package.html#cb122-2" tabindex="-1"></a><span class="do">## (which is enough to compare 2 counterfactual scenarios)</span></span>
<span id="cb122-3"><a href="estimate-the-cde-using-the-ltmle-package.html#cb122-3" tabindex="-1"></a>CDE_ltmle_M0_death<span class="sc">$</span>msm</span></code></pre></div>
<pre><code>## 
## Call:  glm(formula = formula, family = family, data = data.frame(data, 
##     weights), weights = weights, control = glm.control(maxit = 100))
## 
## Coefficients:
##      S1       S2  
## -2.3993   0.6924  
## 
## Degrees of Freedom: 20000 Total (i.e. Null);  19998 Residual
## Null Deviance:       13560 
## Residual Deviance: 144.9     AIC: NA</code></pre>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb124-1" tabindex="-1"></a><span class="do">## You can check the distribution of the g-functions to check the </span></span>
<span id="cb124-2"><a href="estimate-the-cde-using-the-ltmle-package.html#cb124-2" tabindex="-1"></a><span class="do">## positivity assumption</span></span>
<span id="cb124-3"><a href="estimate-the-cde-using-the-ltmle-package.html#cb124-3" tabindex="-1"></a><span class="fu">boxplot</span>(CDE_ltmle_M0_death<span class="sc">$</span>cum.g[,,<span class="dv">1</span>])</span></code></pre></div>
<p><img src="_main_files/figure-html/Psi_CDE_ltmle_bin3-1.png" width="672" /></p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb125-1" tabindex="-1"></a><span class="fu">boxplot</span>(CDE_ltmle_M0_death<span class="sc">$</span>cum.g[,,<span class="dv">2</span>])</span></code></pre></div>
<p><img src="_main_files/figure-html/Psi_CDE_ltmle_bin3-2.png" width="672" /></p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb126-1" tabindex="-1"></a><span class="co"># Note: cum.g indicates the distribution before truncation at 0.01</span></span>
<span id="cb126-2"><a href="estimate-the-cde-using-the-ltmle-package.html#cb126-2" tabindex="-1"></a><span class="co">#       cum.g.unbounded indicates the distribution after truncation at 0.01</span></span>
<span id="cb126-3"><a href="estimate-the-cde-using-the-ltmle-package.html#cb126-3" tabindex="-1"></a></span>
<span id="cb126-4"><a href="estimate-the-cde-using-the-ltmle-package.html#cb126-4" tabindex="-1"></a><span class="do">## The influence curve of the 2 parameters of the MSM are given in the IC matrix</span></span>
<span id="cb126-5"><a href="estimate-the-cde-using-the-ltmle-package.html#cb126-5" tabindex="-1"></a><span class="co"># this is used to calculate the confidence intervals (by delta method)</span></span>
<span id="cb126-6"><a href="estimate-the-cde-using-the-ltmle-package.html#cb126-6" tabindex="-1"></a><span class="fu">summary</span>(CDE_ltmle_M0_death<span class="sc">$</span>IC)</span></code></pre></div>
<pre><code>##        S1                 S2          
##  Min.   :-12.0220   Min.   :-93.3038  
##  1st Qu.: -0.4077   1st Qu.: -0.3192  
##  Median : -0.0760   Median :  0.0154  
##  Mean   :  0.0000   Mean   :  0.0000  
##  3rd Qu.:  0.3235   3rd Qu.:  0.3750  
##  Max.   : 93.6256   Max.   : 56.1813</code></pre>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb128-1" tabindex="-1"></a><span class="do">## the fit$Qstar vector is a list of the fluctuation models</span></span>
<span id="cb128-2"><a href="estimate-the-cde-using-the-ltmle-package.html#cb128-2" tabindex="-1"></a><span class="do">## used to update the initial Qbar function estimated by g-computation</span></span>
<span id="cb128-3"><a href="estimate-the-cde-using-the-ltmle-package.html#cb128-3" tabindex="-1"></a><span class="co"># We can see that each Qbar model have been updated in the TMLE process.</span></span>
<span id="cb128-4"><a href="estimate-the-cde-using-the-ltmle-package.html#cb128-4" tabindex="-1"></a>CDE_ltmle_M0_death<span class="sc">$</span>fit<span class="sc">$</span>Qstar</span></code></pre></div>
<pre><code>## $phys
## 
## Call:  glm(formula = formula, family = family, data = data.frame(data, 
##     weights), weights = weights, control = glm.control(maxit = 100))
## 
## Coefficients:
##        S1         S2  
## -0.000820   0.001433  
## 
## Degrees of Freedom: 10000 Total (i.e. Null);  9998 Residual
## Null Deviance:       11.27 
## Residual Deviance: 11.27     AIC: NA
## 
## $death
## 
## Call:  glm(formula = formula, family = family, data = data.frame(data, 
##     weights), weights = weights, control = glm.control(maxit = 100))
## 
## Coefficients:
##        S1         S2  
## -0.026121   0.004088  
## 
## Degrees of Freedom: 4158 Total (i.e. Null);  4156 Residual
## Null Deviance:       2806 
## Residual Deviance: 2806  AIC: NA</code></pre>
</div>
<div id="for-continuous-outcomes" class="section level3 hasAnchor" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> For continuous outcomes<a href="estimate-the-cde-using-the-ltmle-package.html#for-continuous-outcomes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As previously, for continuous outcomes, the <code>ltmle</code> package transforms the outcome on a 0 to 1 continuous scale, <span class="math inline">\(Y_\text{transformed} = \frac{Y - \min(Y)}{\max(Y) - \min(Y)}\)</span>, so that quasi-binomial parametric models can be used in the computation procedure. Mean predictions are then back-transformed on the original scale.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-1" tabindex="-1"></a><span class="do">## Define the data set with the continuous outcome score</span></span>
<span id="cb130-2"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-2" tabindex="-1"></a>data_continuous <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, <span class="at">select =</span> <span class="fu">c</span>(sex, low_par_edu,</span>
<span id="cb130-3"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-3" tabindex="-1"></a>                                         edu, phys, occupation,</span>
<span id="cb130-4"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-4" tabindex="-1"></a>                                         smoking, score))</span>
<span id="cb130-5"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-5" tabindex="-1"></a><span class="do">## Replace the Qbar function </span></span>
<span id="cb130-6"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-6" tabindex="-1"></a><span class="do">## (the 2d formula should be named score instead of death)</span></span>
<span id="cb130-7"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-7" tabindex="-1"></a>Qform <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">phys =</span> <span class="st">&quot;Q.kplus1 ~ sex + low_par_edu + edu&quot;</span>,</span>
<span id="cb130-8"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-8" tabindex="-1"></a>           <span class="at">score =</span> <span class="st">&quot;Q.kplus1 ~ sex + low_par_edu + phys + occupation +</span></span>
<span id="cb130-9"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-9" tabindex="-1"></a><span class="st">                               edu * smoking&quot;</span>) <span class="co"># add interaction</span></span>
<span id="cb130-10"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-10" tabindex="-1"></a><span class="do">## SuperLearner library</span></span>
<span id="cb130-11"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-11" tabindex="-1"></a>SL.library <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">Q=</span><span class="fu">c</span>(<span class="st">&quot;SL.mean&quot;</span>,<span class="st">&quot;SL.glm&quot;</span>,<span class="st">&quot;SL.interaction.back&quot;</span>,<span class="st">&quot;SL.hal9001.Qbar&quot;</span>),</span>
<span id="cb130-12"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-12" tabindex="-1"></a>                   <span class="at">g=</span><span class="fu">c</span>(<span class="st">&quot;SL.mean&quot;</span>,<span class="st">&quot;SL.glm&quot;</span>,<span class="st">&quot;SL.interaction.back&quot;</span>,<span class="st">&quot;SL.hal9001&quot;</span>))</span>
<span id="cb130-13"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-13" tabindex="-1"></a></span>
<span id="cb130-14"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-14" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb130-15"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-15" tabindex="-1"></a><span class="do">## CDE, setting M=0</span></span>
<span id="cb130-16"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-16" tabindex="-1"></a>CDE_ltmle_M0_score <span class="ot">&lt;-</span> <span class="fu">ltmle</span>(<span class="at">data =</span> data_continuous,</span>
<span id="cb130-17"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-17" tabindex="-1"></a>                            <span class="at">Anodes =</span> <span class="fu">c</span>(<span class="st">&quot;edu&quot;</span>, <span class="st">&quot;smoking&quot;</span>),</span>
<span id="cb130-18"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-18" tabindex="-1"></a>                            <span class="at">Lnodes =</span> <span class="fu">c</span>(<span class="st">&quot;phys&quot;</span>, <span class="st">&quot;occupation&quot;</span>), </span>
<span id="cb130-19"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-19" tabindex="-1"></a>                            <span class="at">Ynodes =</span> <span class="fu">c</span>(<span class="st">&quot;score&quot;</span>),</span>
<span id="cb130-20"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-20" tabindex="-1"></a>                            <span class="at">survivalOutcome =</span> <span class="cn">FALSE</span>, </span>
<span id="cb130-21"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-21" tabindex="-1"></a>                            <span class="at">Qform =</span> Qform,</span>
<span id="cb130-22"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-22" tabindex="-1"></a>                            <span class="at">gform =</span> gform,</span>
<span id="cb130-23"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-23" tabindex="-1"></a>                            <span class="at">abar =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>), <span class="co"># do(A=1,M=0)</span></span>
<span id="cb130-24"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-24" tabindex="-1"></a>                                        <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)), <span class="co">#  do(A=0,M=0)</span></span>
<span id="cb130-25"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-25" tabindex="-1"></a>                            <span class="at">SL.library =</span> SL.library,</span>
<span id="cb130-26"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-26" tabindex="-1"></a>                            <span class="at">estimate.time =</span> <span class="cn">FALSE</span>, <span class="co"># estimate computation time?</span></span>
<span id="cb130-27"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-27" tabindex="-1"></a>                            <span class="at">gcomp =</span> <span class="cn">TRUE</span>,</span>
<span id="cb130-28"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-28" tabindex="-1"></a>                            <span class="at">variance.method =</span> <span class="st">&quot;ic&quot;</span>)</span>
<span id="cb130-29"><a href="estimate-the-cde-using-the-ltmle-package.html#cb130-29" tabindex="-1"></a><span class="fu">summary</span>(CDE_ltmle_M0_score)</span></code></pre></div>
<pre><code>## Estimator:  gcomp 
## Warning: inference for gcomp is not accurate! It is based on TMLE influence curves.
## Call:
## ltmle(data = data_continuous, Anodes = c(&quot;edu&quot;, &quot;smoking&quot;), Lnodes = c(&quot;phys&quot;, 
##     &quot;occupation&quot;), Ynodes = c(&quot;score&quot;), survivalOutcome = FALSE, 
##     Qform = Qform, gform = gform, abar = list(c(1, 0), c(0, 0)), 
##     SL.library = SL.library, estimate.time = FALSE, gcomp = TRUE, 
##     variance.method = &quot;ic&quot;)
## 
## Treatment Estimate:
##    Parameter Estimate:  37.536 
##     Estimated Std Err:  0.34926 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (36.852, 38.221) 
## 
## Control Estimate:
##    Parameter Estimate:  49.66 
##     Estimated Std Err:  0.34266 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (48.989, 50.332) 
## 
## Additive Treatment Effect:
##    Parameter Estimate:  -12.124 
##     Estimated Std Err:  0.4869 
##               p-value:  &lt;2e-16 
##     95% Conf Interval: (-13.078, -11.17)</code></pre>
<p>The controlled direct effect of education on the score outcome, had the mediator been set to 0 for every participant, estimated by TMLE is -12.12, 95%CI=[-13.08, -11.17].</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-vanderweele2009" class="csl-entry">
VanderWeele, Tyler J. 2009. <span>“Marginal Structural Models for the Estimation of Direct and Indirect Effects.”</span> <em>Epidemiology</em> 20: 18–26.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="estimate-the-ate-by-tmle.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="estimate-rnde-and-rnie-by-double-robust-estimators.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": false,
    "twitter": false,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/benoitlepage/Inserm_workshop_282/04-CDE_by_tmle.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
